### ISSUE TITLE
package_coverage is failing with all(lengths(others) == length(x)) is not TRUE

### ISSUE THREAD

**Issue by RomanTsegelskyi** [r-lib/covr#177]
I am working on a `R` package - https://github.com/allr/testr and `covr::package_coverage()` is simply failing with `all(lengths(others) == length(x)) is not TRUE`. I see that the failure is happening in `merge_coverage` but I can't figure out why is that happening.

**Comment by RomanTsegelskyi** [comment]
I figure it out, the tests that are causing problems are calling covr functions in them

**Comment by RomanTsegelskyi** [comment]
Is it possible to handle such case?

**Comment by HenrikBengtsson** [comment]
I also get this error, cf. https://travis-ci.org/HenrikBengtsson/future.BatchJobs/jobs/137683772#L679.  

In my case the [error occurs in `covr:::merge_coverage()`](https://github.com/jimhester/covr/blob/master/R/covr.R#L262) because some of the trace files have empty results, e.g.
```r
> a <- readRDS("covr_trace_381a503d3cf7")
> str(as.list(a))
List of 2
 $ utils.R:118:3:118:42:3:42:1930:1930:List of 1
  ..$ value: num(0) 
 $ utils.R:119:3:119:25:3:25:1931:1931:List of 1
  ..$ value: num(0) 
```
whereas a "normal" trace file has elements containing also fields `srcref` and `functions`, e.g.
```r
> b <- readRDS("covr_trace_38705183b4bc")
> str(as.list(b)[1])
List of 1
 $ BatchJobsFuture-class.R:107:3:112:3:3:3:109:114:List of 3
  ..$ value    : num 0
  ..$ srcref   :Class 'srcref'  atomic [1:8] 107 3 112 3 3 3 109 114
  .. .. ..- attr(*, "srcfile")=Classes 'srcfilealias', 'srcfile' <environment: 0xb7837e0> 
  ..$ functions: chr "print.BatchJobsFuture"
```
This give the error, i.e.
```r
> objs <- list(as.list(x), as.list(b))
> x <- objs[[1]]
> others <- objs[-1]
> stopifnot(all(lengths(others) == length(x)))
Error: all(lengths(others) == length(x)) is not TRUE
```

**Comment by kforner** [comment]
This PR should/could solve your problem: https://github.com/jimhester/covr/pull/202

**Comment by HenrikBengtsson** [comment]
I've created PR #221 to fix (=workaround this) this.  PR #202 was not enough.

**Comment by frbl** [comment]
I still have an issue that might be related to this. Running `Rscript -e 'covr::codecov()'` gives me:
```bash
Error: all(lengths(others) == length(x)) is not TRUE
Execution halted
```

I tried to apply the earlier, now reverted patches and that didn't work. I opened up a debugger and the lengths indeed look rather different:
```
Browse[1]> length(objs[[1]])
[1] 512
Browse[1]> lengths(objs[-1])
[1] 860
```
I'm not really in the code, so I don't know why this might happen.

**Comment by frbl** [comment]
Just in case anyone else runs into this, I apparently had a `devtools::load_all()' in my test file for some reason. Removing this line obviously solved my problem.
