### ISSUE TITLE
Rcpp exports headers to inst/include which also need to be excluded by default

### ISSUE THREAD

**Issue by jackwasey** [r-lib/covr#217]
#170 describes excluding RcppExports files. I let `Rcpp` generate headers, so I also get this file, which I think you would want also to exclude.

`inst/include/icd_RcppExports.h`

Hopefully it will be trivial for you to exclude
`inst/include/.+_RcppExports.h` or similar using `rex` :-)

I don't `#include` my own headers, and I get 0% coverage of this file.

**Comment by jimhester** [comment]
This should now be easy for you to setup in your repository with a `.covrignore` file. https://github.com/r-lib/covr#covrignore-file
