### ISSUE TITLE
zero_coverage() throws "Error in normalizePath[...]" if there's any line with zero coverage

### ISSUE THREAD

**Issue by Filip-Michalowski** [r-lib/covr#234]
### Issue
If there's a file inside the project that has a line **not** covered by tests, attempting to run zero_coverage() throws following error:

    Error in normalizePath(path.expand(path), winslash, mustWork) : 
      path[1]="R/<filename>.R": <localized "System can't find specified path" message>

### Minimal reproducible example
I have attached a sample project ([mrp.zip](https://github.com/jimhester/covr/files/606292/mrp.zip)) that has one sample covered file (`hello.R`) and one sample not covered file (`niepokryty.R`). NB that adding non-covered lines to `hello.R` 

Output of tally_coverage(), printed:

    > print(tally_coverage(package_coverage("mrp")))
            filename  functions line value
    8      R/hello.R      hello   17     2
    1 R/niepokryty.R niepokryty    5     0
    2 R/niepokryty.R niepokryty    6     0
    3 R/niepokryty.R niepokryty    7     0
    4 R/niepokryty.R niepokryty    9     0
    5 R/niepokryty.R niepokryty   10     0
    6 R/niepokryty.R niepokryty   12     0
    7 R/niepokryty.R niepokryty   15     0

Output of zero_coverage():

    > zero_coverage(package_coverage("mrp"))
    Error in normalizePath(path.expand(path), winslash, mustWork) : 
      path[1]="R/niepokryty.R": System nie może odnaleźć określonej ścieżki

**Comment by jimhester** [comment]
Is it possible your project is on a network share? `base::normalizePath()` has known issues working with windows network shares.

**Comment by Filip-Michalowski** [comment]
No, the problem appeared on local disk. When I add tests that cover all lines, the problem goes away, and it comes back when I add non-covered code again.

So, I'm assuming there are no errors when you run `zero_coverage()` on that project on your machine and there might be an issue with my setup. Is that correct?

**Comment by Filip-Michalowski** [comment]
Hm.

For what's it worth, after rebooting:

- calling `zero_coverage(package_coverage("<package name>"))` with working directory set one level above the project folder still results in that error,
- but calling `zero_coverage(package_coverage())` (ie. no arguments) with working directory set inside the project folder Works as Intended.

This behaviour persists even after moving the project to a different partition.
