### ISSUE TITLE
Get coverage results per file as vector

### ISSUE THREAD

**Issue by chen-liang-oracle** [r-lib/covr#241]
As discussed, it would be better to have a vector type of output added to the `percent_coverage()` function. Related code for the output could leverage the `tally_coverage()` function like:

```
> co <- covr::package_coverage("<path_to_package_name>")
> df <- covr::tally_coverage(as.data.frame(co))
> filecoverage <- tapply(df$value, df$filename, FUN=function(x) (sum(x > 0) / length(x)) * 100)
> totalcoverage <- sum(df$value > 0) / nrow(df) * 100
```

**Comment by jimhester** [comment]
Closed by https://github.com/r-lib/covr/pull/282
