### ISSUE TITLE
files not included in the final coverage result

### ISSUE THREAD

**Issue by chen-liang-oracle** [r-lib/covr#243]
I have two files which are not included in the package coverage result, the first file contain a group of `setClass()` functions to define S4 classes, like:
```
setClass("ore.integer",
  prototype = prototype(integer()),
  contains = "ore.number"
)
```
The second file contains assign function with some defined mathematical constants, like:
```
ore.const <- new.env()
assign(".set",
       function(x, value)
       {
           assign(x, as.numeric(value), ore.const)
           lockBinding(x, ore.const)
       },
       ore.const)
### math.h related constants
ore.const$.set("E",        "2.71828182845904523536028747135266250") # e
```
Any idea why these two files are not included in the coverage result?

**Comment by brodieG** [comment]
Likely related to #113

**Comment by jimhester** [comment]
So in both of these cases there is no code being run during the tests, so even if we were tracking coverage for these files they would be uncovered.
