### ISSUE TITLE
Code coverage calculation hangs when executing parallel code on Travis CI

### ISSUE THREAD

**Issue by p-smirnov** [r-lib/covr#270]
I am experiencing an issue in calculating the code coverage for our Bioconductor package PharmacoGx. It is very similar to one I had with executing testthat when trying to calculate test coverage, but the workaround which succeeded for testthat does not seem to help with running codecov. The test that issue is below:
https://github.com/hadley/testthat/issues/602

The issue specifically is that when running `codecov` interactively on my machine,  it runs fine in about 15 minutes and outputs results. However, when run on Travis CI, the code hangs for over an hour, and does not produce output. I have narrowed the appearance of the issue down to adding this test:
```
library(PharmacoGx)
require(parallel)
context("Checking intersectPSet.")
test_that("Intersection result did not change since last time", {
	data(GDSCsmall)
	data(CCLEsmall)
	expect_equal_to_reference(intersectPSet(list('GDSC'=GDSCsmall, 'CCLE'=CCLEsmall), intersectOn = c("drugs", "cell.lines","concentrations")), "intersectedSmallData.rds")
})
```

The function `intersectPSet` contains a call to `makeCluster` and `parSapply`. In the case of testthat, the issue was that R CMD check was setting a environmental variable `Sys.setenv(R_TESTS="startup.Rs")`, using a relative path, and the file startup.Rs did not exist in the tests/testthat directory. I believe the parallel workers spawned with that as their working directory, causing the issue. Two workarounds proposed were to create this file as empty in the right directory, or to add `Sys.unsetenv("R_TESTS")` to the beginning of the `testthat.R` script. I have applied both in hopes one of the two would help with the issue of `codecov` hanging, but neither seems to have any effect. I suspect this has to do with how codecov sets up the environment where it does its tests when running on Travis CI.

(The issue was discussed on R PKG devel mailing list: https://stat.ethz.ch/pipermail/r-package-devel/2017q1/001316.html)

Could someone with more knowledge of the covr package take a look? It would be great if I could reproduce the hanging on my own machine but it seems to only happen on Travis, making debugging tricky.

**Comment by jimhester** [comment]
I am not sure what is going on, but it looks like you have a workaround.
