### ISSUE TITLE
package_coverage fails if testthat::test_path is used in test files

### ISSUE THREAD

**Issue by jgabry** [r-lib/covr#283]
This came up over at https://github.com/stan-dev/bayesplot/issues/114 :

Because `testInstalledPackage` runs tests in a _pkg_-tests subdirectory any usage of the `test_path` function from `testthat` within test files causes the error

```
Error: Can't find `tests/testthat/` in current directory.
```

when `package_coverage` is run. Removing the usage of `test_path` gets rid of the problem.

Unless I've missed it somewhere (in which case sorry!), this isn't documented. `test_path` is probably used widely enough that a warning about this could be a good addition to the documentation.

**Comment by jimhester** [comment]
This is fixed in the devel version of testthat https://github.com/hadley/testthat/issues/542.

**Comment by jgabry** [comment]
Ok great. I looked through the testthat issues but somehow missed that one. Thanks for the pointer.
