### ISSUE TITLE
Help with error

### ISSUE THREAD

**Issue by chris-prener** [r-lib/covr#284]
hi @jimhester - I've just started using `covr` and have been running into an error. My [package](https://github.com/chris-prener/testDriveR) passes the `R CMD check` (using `devtools`) and builds just fine on Travis CI and Appveyor. 

However, when I added `Rscript -e 'covr::codecov()'` to my `.travis.yml` file, I started getting errors on codecov.io.

I've tried to debug the unit tests to identify the problem using `covr::package_coverage(type = "all", quiet = FALSE, clean = FALSE)` and I get this (abbreviated) output:

```
Testing examples for package ‘testDriveR’
Running specific tests for package ‘testDriveR’
  Running ‘testthat.R’
Error: identical(names(y), names) is not TRUE
```

My google searches have turned up empty regarding what that error actually means... any help you can provide would be much appreciated!

**Comment by jimhester** [comment]
Your package does not contain any R code, so there is nothing to measure coverage on.

**Comment by chris-prener** [comment]
thanks @jimhester - I think my confusion stemmed from "there are `.R` files in there so that is R code"! It needs to be functions, then for `codecov()` to do its job?

**Comment by jimhester** [comment]
Yes, there needs to be R functions or else there is nothing to measure coverage on.

**Comment by chris-prener** [comment]
perfect - thanks @jimhester!
