### ISSUE TITLE
Exclusion comments not working

### ISSUE THREAD

**Issue by asardaes** [r-lib/covr#286]
[Here](https://github.com/asardaes/dtwclust/blob/master/codecov.R) is the script that calls `codecov`, and [this](https://github.com/asardaes/dtwclust/blob/master/.travis.yml#L29) is how it is called in TravisCI.

Neither [single-line](https://codecov.io/gh/asardaes/dtwclust/src/6f0075b873af4f28f6776527750c3009dac1fa47/R/tsclust.R#L311) nor [range](https://codecov.io/gh/asardaes/dtwclust/src/6f0075b873af4f28f6776527750c3009dac1fa47/R/tsclust.R#L347) exclusions seem to be working.

**Comment by jimhester** [comment]
You are setting the covr exclude options incorrectly (https://github.com/asardaes/dtwclust/blob/master/codecov.R#L2)

They are regular expressions of patterns to match, not boolean values. If you want the defaults (which is what you are using in the code) remove that line entirely.
