### ISSUE TITLE
Functions wrapped in `covr:::count()`: an edge case

### ISSUE THREAD

**Issue by wlandau-lilly** [r-lib/covr#289]
In my unit tests, `covr` wraps my functions in calls to `covr:::count()`. This is usually harmless, but it interferes with the static code analysis that [drake](https://github.com/wlandau-lilly/drake) uses to track a user's workflow. I found that out when I saved the `visNetwork` workflow DAG to a file during a test  (`drake::plot_graph()`). In the middle of the graph below, I was hovering over `reg1()` (near the middle), which revealed that the function body of `reg1()` was wrapped in a call to `covr:::count()`. Is there anything I can do to prevent some functions from being wrapped? Maybe with a protected environment?

![covr](https://user-images.githubusercontent.com/22958003/32411612-2db6c0d6-c1b6-11e7-8330-6c4c1fec307b.png)

**Comment by jimhester** [comment]
No there isn't really anything you can do to prevent this at the moment, sorry!
