### ISSUE TITLE
path error with covr but not with testthat

### ISSUE THREAD

**Issue by lorenzwalthert** [r-lib/covr#290]
I came accross a very strange example, in which testthat works but codecov does not. I tried to minimalize the example as much as possible and created a package `reprexpkg` that contains just one test that works with testthat but not with codecov.
Essentially, the following test in is the problem

```r
test_that("test with tempdir", {
  dir <- tempfile("styler")
  dir.create(dir)
  path_temp <- file.path(dir, "repeated_parsing-in.R")
  path_perm <- rprojroot::find_testthat_root_file("repeated_parsing-in.R")
  file.copy(path_perm, dir)
  path_out <- gsub("\\-.*$", "\\-in\\.R", path_perm)
  identical(path_out, path_perm)
  #> TRUE
  ref <- enc::read_lines_enc(path_perm) # does not work with path_out, only works with path_term
  unlink(dir)
})
```
As soon as you replace `path_perm` with `path_out` (which ought to be identical), calling `covr::package_coverage()` won't work anymore but `devtools::test()` still does.
```r
> test_check("reprexpkg")
[1] "Hello, world!"
1. Error: test with tempdir (@test-test.R#14) -----------------------------------------------------------
cannot open the connection
1: enc::read_lines_enc(path_out) at testthat/test-test.R:14
2: readLines(con, warn = FALSE, n = n, ok = ok, skipNul = skipNul, encoding = "UTF-8")

testthat results =========================================================================================
OK: 2 SKIPPED: 0 FAILED: 1
1. Error: test with tempdir (@test-test.R#14) 

Error: testthat unit tests failed
Execution halted
```

Any ideas why that happens and how one could fix it? Any help would be appreciated, although we found a workaround already. You can clone the package from here to reproduce the error (however, I can understand it if it's too much of work): https://github.com/lorenzwalthert/reprexpkg

**Comment by lorenzwalthert** [comment]
Reference: https://github.com/r-lib/styler/issues/272
cc: @krlmlr

**Comment by jimhester** [comment]
`devtools::test()` is not what `R CMD check` or covr runs, it is not a correct reproduction. You need to use `devtools::check()`, or even better `R CMD build . && R CMD check *tar.gz` from the command line to get a more accurate reproduction without covr.

Regardless I cannot reproduce your error from reprexpkg. I get 100% coverage on the package.

Likely the reason you were running into issues is that your tests assumed the tests were being run in the `tests` directory, and `tools::testInstalledPackages()` which is what covr uses to run tests copies the tests to `pkgname-tests` and runs the tests from there.

**Comment by lorenzwalthert** [comment]
Ok, thanks for looking at it. So I assume you have replaced the offending line 
```r
ref <- enc::read_lines_enc(path_perm)
```
in `tests/testthat/test-test.R` with 
```r
ref <- enc::read_lines_enc(path_out)
```
(Sorry I probably should have committed it so it produces the error right away). I used the dev version `3.0.0.9000` of `covr`.

I tried to avoid assuming the tests were ran into the `tests` directory, which is why I used `rprojroot::find_test_that_root_file()` and with that everything works. The problem is really that when I replace the last part in the path with what is already there, i.e.
```r
path_perm
#> ".../reprexpkg/tests/testthat/repeated_parsing-in.R"
path_out <- gsub("\\-.*$", "\\-in\\.R", path_perm)
# then use path_out instead of path_perm
```
The error occurs.

**Comment by lorenzwalthert** [comment]
I added travis where the same problem occurs: All tests pass (apparently checking with `R CMD check reprexpkg_0.1.0.tar.gz --as-cran --no-manual --no-manual --no-manual --no-manual`) but codecov does not work.
https://travis-ci.org/lorenzwalthert/reprexpkg/builds/298797044?utm_source=email&utm_medium=notification

**Comment by krlmlr** [comment]
@lorenzwalthert: Is this still a problem?

**Comment by lorenzwalthert** [comment]
I just restarted the build process so we can see whether the problem is still there (potentially with never R / covr CRAN versions) . https://travis-ci.org/lorenzwalthert/reprexpkg.

**Comment by lorenzwalthert** [comment]
Ok, it seems to be there [still](https://travis-ci.org/lorenzwalthert/reprexpkg/jobs/298801293#L1938).

**Comment by krlmlr** [comment]
Are you sure that both paths evaluate to the same thing when *covr* is run?

https://github.com/lorenzwalthert/reprexpkg/blob/997e7fcc793d7ae7aa7927d9db16eeadfa0a1fe8/tests/testthat/test-test.R#L12-L13

**Comment by lorenzwalthert** [comment]
Well I guess that's the whole point that they don't but I don't know why. I think it might be related to what Jim says in his last paragraph about tests being run in some others directory.

**Comment by krlmlr** [comment]
Maybe a regex that captures too eagerly? Can you try:

```r
path_out <- gsub("\\-[^-]$", "\\-in\\.R", path_perm)
# or, without escaped dashes
path_out <- gsub("-[^-]$", "-in\\.R", path_perm)
```

**Comment by lorenzwalthert** [comment]
Now covr [works](https://travis-ci.org/lorenzwalthert/reprexpkg/jobs/363571820#L1158) with 
```r
path_out <- gsub("\\-[^-]*$", "\\-in\\.R", path_perm)
```
