### ISSUE TITLE
0% coverage reported on Windows

### ISSUE THREAD

**Issue by maelle** [r-lib/covr#291]
I am using the development version of `covr` which solved [this issue](https://github.com/r-lib/covr/issues/223) I had with a previous version.

When running `covr::package_coverage()` for [this package with tests](https://github.com/wlandau-lilly/drake) I get 0% coverage which puzzles me given 1) [codecov results](https://codecov.io/github/wlandau-lilly/drake?branch=master) 2) the fact that tests actually run on my laptop via `devtools::test()`.

I am not sure which info to include in this issue. :-)

**Comment by wlandau-lilly** [comment]
@maelle I could not reproduce this issue with 3c24869cf6a78c3640162a649bc1b7a51fe76de6, 32-bit R-devel (2017-09-23 r73342), and Windows 7. Do you also get 0% coverage with other packages?

```r
> sessionInfo()
R Under development (unstable) (2017-09-23 r73342)
Platform: i386-w64-mingw32/i386 (32-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
[1] covr_3.0.1

loaded via a namespace (and not attached):
[1] compiler_3.5.0 lazyeval_0.2.1 magrittr_1.5   rex_1.1.2     
[5] tools_3.5.0    withr_2.1.0    rstudioapi_0.7 yaml_2.1.14   
[9] crayon_1.3.4 
```

**Comment by maelle** [comment]
Good question, yes I get it with other packages, I have just tried that.

I get this warning

```r
Warning messages:
1: running command 'C:/PROGRA~1/R/R-34~1.0PA/bin/x64/R --vanilla CMD config CC' had status 1 
2: running command 'C:/PROGRA~1/R/R-34~1.0PA/bin/x64/R --vanilla CMD config CC' had status 1 
```

```r
> sessionInfo()
R version 3.4.0 Patched (2017-05-10 r72669)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.4.0 lazyeval_0.2.0 magrittr_1.5   rex_1.1.2      tools_3.4.0   
[6] withr_2.1.0    rstudioapi_0.6 crayon_1.3.4   covr_3.0.1 

```

will update `lazyeval` and `rstudioapi`.

**Comment by maelle** [comment]
Update: updating these two packages didn't make a difference.

**Comment by wlandau-lilly** [comment]
I tried to meet you half-way: 64-bit R 3.4.0. After `update.packages()`, I got 100% coverage on [this package](https://github.com/wlandau-lilly/eply) (quicker to test).

From the warning messages, I see your R installations are in `C:/Program Files/R/`. For different issues, the space in that path was the culprit, so now I keep all my R versions in `C:/R/`. Not sure if it would help in this case, but if `covr` is spawning child processes, it might.

**Comment by maelle** [comment]
Oh interesting! I'm not going to change the R location right now, but it's good to know.

**Comment by wlandau-lilly** [comment]
I am glad you did not jump at the suggestion because `C:/Program Files/` does not seem to be the problem. I tried installing R 3.4.2 there, and I still got the expected full coverage.

**Comment by jimhester** [comment]
@maelle can you try running `system("C:/PROGRA~1/R/R-34~1.0PA/bin/x64/R --vanilla CMD config CC")` directly? I think this is an issue with interpreting short names on the OS, not sure what the solution is, we have similar issue in devtools (https://github.com/hadley/devtools/issues/885) with some possible user side fixes.

**Comment by maelle** [comment]
`

> system("C:/PROGRA~1/R/R-34~1.0PA/bin/x64/R --vanilla CMD config CC") 
"sh" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
Warning message:
running command 'C:/PROGRA~1/R/R-34~1.0PA/bin/x64/R --vanilla CMD config CC' had status 1 `

So `sh` is not recognized, whatever that means?

**Comment by wlandau-lilly** [comment]
What if you updated `Rtools`? It's a shot in the dark, but it seems like the easiest next thing.

**Comment by randomsven** [comment]
... just to avoid "special moments" - I also had a similar problem to you (if I read correctly): running covr on a collection of R scripts on Windows (red herring) produced 0 coverage. The code I was trying to check test coverage for was being migrated into a package, but was originally a set of scripts - tests had to leverage the source function to drag sets of functions in, which overwrites the code that has been instrumented by covr - getting rid of any source statements and building the package solved the problem. ... not saying this is your issue, but it had me stumped for a little while :)

**Comment by rnobleeddy** [comment]
If it helps, I have the exact same issue as @maelle . Not sure there's much I can add, but I'd be happy to try out any suggestions anyone has?

**Comment by maelle** [comment]
@wlandau-lilly Thank you, I just ran `installr::install.Rtools()` that told me I have the relevant version installed. 🤔 

@randomsven Thanks but in my case the exact same packages gets a different coverage on other systems. :wink:

@rnobleeddy Thank you, I'm happy to not be alone in this position and I hope we'll soon get it sorted out!

**Comment by aelhabr** [comment]
I'm having the same issue.

**Comment by thomaslaber** [comment]
Same here.

**Comment by idefer** [comment]
I don't know if it may be related, but I was getting the same issue while running `file_coverage()` with one source file and one test file. It turned out, I had `rm(list = ls())` at the top of the test file to clean up the environment before running the tests. Removing it fixed the issue.

**Comment by hartmast** [comment]
I have the same issue on a Mac, both with the CRAN and the Github versions; I tried running `package_coverage()` on several different packages.

```
> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: OS X El Capitan 10.11.5

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] compiler_3.4.3 lazyeval_0.2.1 magrittr_1.5   rex_1.1.2      tools_3.4.3    withr_2.1.1    rstudioapi_0.7
 [8] yaml_2.1.16    crayon_1.3.4   covr_3.0.1
```

**Comment by q23qweliuhan** [comment]
I got similar issue here, just create a new package with the hello.R, and created test using use_test(). 
If I run package_coverage(), it shows:
test Coverage: 0.00%
R/hello.R: 0.00%
Warning messages:
1: running command 'C:/Users/hangliu/DOCUME~1/R/R-34~1.2/bin/x64/R --vanilla CMD config CC' had status 127 
2: running command 'C:/Users/hangliu/DOCUME~1/R/R-34~1.2/bin/x64/R --vanilla CMD config CC' had status 127

**Comment by jimhester** [comment]
So I think these errors tend to occur because covr expects that R and RTools are installed on your PATH. If they are not you need to use something like `devtools::setup_rtools()` to put it on the PATH prior to running covr.

**Comment by jimhester** [comment]
This should now be fixed, although you may still get similar installation errors if you try to run covr on a package needing compilation without Rtools being on the path.
