### ISSUE TITLE
set environment variable if covr is running

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/covr#293]
I have some stress tests in `processx` (e.g. (re)starting many processes quickly, etc), and it does not really make too much sense to run these for the test coverage, or at least I would not repeat them many times. 

So it would be handy if I could detect if covr is running, e.g. `covr` could set an environment variable. I can send a PR if this is OK.

**Comment by jimhester** [comment]
Yes, covr sets `R_COVR` https://github.com/r-lib/covr/commit/95628104f04b4fe4c108474c1997866381e2b814 when it is running that you can use.
