### ISSUE TITLE
`report()` fails for certain packages only

### ISSUE THREAD

**Issue by evanbiederstedt** [r-lib/covr#298]
This seq.default error has been reported in previous issues, e.g. https://github.com/r-lib/covr/issues/56
but the solutions discussed does not work for me. 

I'm using the latest version of MacOS:

```
> #within package root
> library(covr)
> report()
Error in seq.default(df[i, "first_line"], df[i, "last_line"]) : 
 'from' cannot be NA, NaN or infinite
> package_coverage()
Error in seq.default(dots[[1L]][[840L]], dots[[2L]][[840L]]) : 
      'from' cannot be NA, NaN or infinite
```

This is odd, as `report()` works perfectly well on the same OS within different package root directories. 

Are there any troubleshooting tips for this?

**Comment by jimhester** [comment]
You will have to supply us with the package you are trying to run report on to have any hope of debugging the issue.

**Comment by evanbiederstedt** [comment]
@jimhester 

Thanks for the speedy reply. Please see the latest push to this repo

https://github.com/mskilab/bamUtils

**Comment by jimhester** [comment]
covr has to use heuristics for conditionals which do not have braces and they were apparently failing for your very nested example used in **bamUtils**. A simple workaround is to use braces for the conditionals.

**Comment by evanbiederstedt** [comment]
> A simple workaround is to use braces for the conditionals, which is what I did in the pull request.

Good to know. Thanks for the help
