### ISSUE TITLE
Using `covr` on Linux; 'Couldn't get a file descriptor referring to the console'

### ISSUE THREAD

**Issue by evanbiederstedt** [r-lib/covr#300]
So, the package is installed and I'm running within the rootdir using the OS Linux

```
> library(covr)
> report()

> Couldn't get a file descriptor referring to the console

```

This is a common error discussion on SO, e.g. 

https://stackoverflow.com/questions/42463929/couldnt-find-a-file-descriptor-referring-to-the-console-on-ubuntu-bash-on-win

I think I should be able to set up an alias to call `open` as `covr` expects. However, this in my bash_profile didn't work

    alias open="xdg-open" 

Is there a way to run `covr` on Linux?

**Comment by jimhester** [comment]
`covr::report()` simply calls the function defined in 'viewer', e.g. `getOption("viewier", utils::browseURL)`, so if that option is not defined it calls `utils::browseURL` on the file.

If opening a viewer is problematic you can use `file <- covr::report(browse = FALSE)` and then view the HTML file in `file` however you are able.
