### ISSUE TITLE
Clarification: testing non-exported functions

### ISSUE THREAD

**Issue by evanbiederstedt** [r-lib/covr#301]
Hi there

Issue as I'm in need of clarification. R packages will often have non-exported functions; these could be internal functions used by other functions, or just functions the author (for whatever reason) would not like to make accessible to the user. 

When I calculate the coverage of my tests in `package_root/tests/testthat`, `covr` naturally counts these functions in the coverage. 

Now. it's been detailed in the README that I could exclude these internal functions via `.covrignore` or line exclusions. However, let's say I would like to test these non-exported functions via `testthat` and have the `covr` hit these. Is that possible? How would I do that without exporting the functions?

**Comment by jimhester** [comment]
testthat tests are run from your packages environment, so all defined objects are available. Therefore you can call and test non-exported functions like any other function.

**Comment by evanbiederstedt** [comment]
Thanks for the response. 

I'm still a bit confused. 

Here is a concrete example. This is a tiny function I've defined and I do not use `#' @export`, so it's not in the package NAMESPACe, but the function is used. 

https://github.com/mskilab/gGnome/blob/master/R/gGnome.R#L7233-L7246

When I try testing this, there's a problem 

```
> test_that('setxor', {
+     A = c(1, 2, 3)
+     B = c(1, 4, 5)
+     expect_equal(setxor(A, B), c(2, 3, 4, 5))
+ })

Error: Test failed: 'setxor'
* could not find function "setxor"
1: expect_equal(setxor(A, B), c(2, 3, 4, 5)) at :4
2: quasi_label(enquo(object), label)
3: eval_bare(get_expr(quo), get_env(quo))
> 
> 
```

**Comment by jimhester** [comment]
use `devtools::load_all()` before running the tests to simulate the environment used when running tests.

**Comment by evanbiederstedt** [comment]
You're right!
Excellent

Do I need to do anything special for these functions to be accessible via Travis? I think in previous github pushes, tests of non-exported functions have failed.

**Comment by jimhester** [comment]
No

**Comment by evanbiederstedt** [comment]
It looks like you're right. Thanks for the clarification!
