### ISSUE TITLE
AppVeyor missing job id 

### ISSUE THREAD

**Issue by kkmann** [r-lib/covr#303]
Hi,

I tried to use covr with appveyor on a little project (https://github.com/kkmann/vanElteren) using appveyor integration (works fine). Uploading the coverage results does fail, however. 

covr seems to be complaining about a missing job ID. Looking through the sources I saw that Travis does use a job ID env variable. Appveyor also provides this [see](https://www.appveyor.com/docs/environment-variables/). Did I screw up something here is it a bug?

My [appveyor.yml](https://github.com/kkmann/vanElteren/blob/master/appveyor.yml).

**Comment by jimhester** [comment]
I think the auto detection doesn't work in Appveyor for some reason, I have had success explicitly adding the `CODECOV_TOKEN` to the environment variables of the job.

**Comment by RolandASc** [comment]
I have fixed this and provided a pull request https://github.com/r-lib/covr/pull/299, if someone would take a few minutes to look into that.
Apols for not having created an issue first, but since I had anyways already fixed it at my end, I thought I'd just pass back a PR.

**Comment by kkmann** [comment]
Hey, thx for addressing this so quickly - and for an overall amazing package!
