### ISSUE TITLE
error in coveralls()

### ISSUE THREAD

**Issue by zkamvar** [r-lib/covr#313]
Hello,

I just noticed that my coverage hasn't been calculated in about a month and I saw that there is an error in the logs:

https://travis-ci.org/grunwaldlab/poppr/jobs/374023653#L1384

```
Rscript -e 'library(covr);coveralls(line_exclusions = list("R/global_memory.r", "R/zzz.r" = 1:118, "R/imsn.R"), function_exclusions = "getfile")'
Error in vapply(X, FUN, ..., FUN.VALUE = character(1)) : 
  values must be length 1,
 but FUN(X[[3459]]) result is length 0
Calls: coveralls ... as.data.frame -> as.data.frame.coverage -> vcapply -> vapply
Execution halted
```

Have you seen this one? Do you know what could be going on? I may have inadvertently borked something here.

**Comment by jimhester** [comment]
No I have have not seen it, see if you can reproduce it by running `as.data.frame(covr::package_coverage())` on your package locally.

**Comment by zkamvar** [comment]
Here's the code to reproduce the behavior in the binder session:


```r
library("covr")
package_coverage(line_exclusions = list("R/global_memory.r", "R/zzz.r" = 1:118, "R/imsn.R"), function_exclusions = "getfile")
package_coverage(line_exclusions = list("R/global_memory.r", "R/zzz.r" = 1:118, "R/imsn.R"))

```

**Comment by jimhester** [comment]
This seems to be working ok now, I cannot reproduce the error with devel covr and the files seem to be excluding as expected.

**Comment by zkamvar** [comment]
It is working as I expected! Thank you!
