### ISSUE TITLE
Error in readRDS(files[i]) : error reading from connection

### ISSUE THREAD

**Issue by wlandau** [r-lib/covr#315]
On Travis, my tests pass, but `codecov()` fails: https://travis-ci.org/ropensci/drake/builds/374837082#L1293.

**Comment by jimhester** [comment]
Could you run `covr::package_coverage()` locally to try and reproduce this?

**Comment by wlandau** [comment]
Locally, `covr::package_coverage("drake")` runs normally. No errors, warnings, or messages. My session info is the same as for #314.

**Comment by wlandau** [comment]
The problem went away in further commits to my repo. I do not know why. Closing.

**Comment by randy3k** [comment]
I see the same error in Github Actions: https://github.com/REditorSupport/languageserver/runs/287088810

**Comment by randy3k** [comment]
On the next build, the same error was seen on macOS but not the linux as above. The error was popping out randomly, not sure how it happens.

I was also able to reproduce it locally once.

**Comment by randy3k** [comment]
I may have figured out the culprit. `callr::r_bg` was used in my package and it seems that the background process sometimes was killed when it was writing the rds file and left a corrupted file. It also explains the random nature of the error. Checking the process status carefully before quiting seems to fix the issue.
