### ISSUE TITLE
Consecutive lines of "conditional w/o braces" create a degenerate coverage object

### ISSUE THREAD

**Issue by jennybc** [r-lib/covr#317]
This function:

``` r
upper_bound <- function(x, y) {
  nx <- length(x)
  ny <- length(y)
  if (nx + ny == 0) return()
  if (nx == 0) return(y[[ny]])
  if (ny == 0) return(x[[nx]])
  comp <- seq_len(min(nx, ny))
  res <- x[comp] == y[comp]
  if (!any(res)) return()
  x[[max(which(res))]]
}
```

is creating a degenerate entry in the coverage object that then cannot printed, `report()`'d, etc. The consecutive lines of brace-less `if()`s seem to be the problem. I can make the problem go away by adding braces. Working hypothesis: if you have `n` such consecutive lines, you need to add braces in the last `n-1` lines. Consistent with my interventions and with the fact that a single, isolated use of such a line is not a problem.

Example of a degenerate entry in the object returned by `package_coverage()`.
<img width="607" alt="screen shot 2018-05-10 at 8 51 54 am" src="https://user-images.githubusercontent.com/599454/39882046-907ad5c2-5437-11e8-859a-177b5260121b.png">

**Comment by jimhester** [comment]
Unfortunately this function alone does not seem sufficient to trigger the bug :(

**Comment by jennybc** [comment]
Please accept my entry for World's Worst Reprex 🤣

Check out googlesheets4 from this commit (or probably any commit, frankly):
https://github.com/tidyverse/googlesheets4/commit/187e39a6104d5325de02598b006a039ec2b1f5fd

And remove the extra braces here:
https://github.com/tidyverse/googlesheets4/blob/187e39a6104d5325de02598b006a039ec2b1f5fd/R/ctype.R#L234-L236

And try to print or run `report()` on the package coverage object:

``` r
print(covr::package_coverage("~/rrr/googlesheets4"))
#> Error in seq.default(dots[[1L]][[47L]], dots[[2L]][[47L]]): 'from' must be a finite number
```

Created on 2018-05-16 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by jimhester** [comment]
This should be fixed now!

<img width="921" alt="screenshot 2018-05-18 11 44 02" src="https://user-images.githubusercontent.com/205275/40244800-dabe3ee8-5a91-11e8-95db-3417dc09db68.png">

**Comment by jennybc** [comment]
Nice! Obscure!
