### ISSUE TITLE
Use GitLab internal pages

### ISSUE THREAD

**Issue by surmann** [r-lib/covr#327]
Is it possible to use `covr` with the internal pages on GitLab? For me it would be fine, to have everything integrated. I think, the only missing feature, is the creation of local static html files.

[Here](https://about.gitlab.com/2016/11/03/publish-code-coverage-report-with-gitlab-pages/) GitLab describes how to publish an coverage report.

**Comment by surmann** [comment]
Sorry, this is available via `report()`, I think.

**Comment by jimhester** [comment]
From reading the document you should be able to use `report()` to generate the html which you can then serve.

If you get this working and would be willing to submit a PR with a `covr::gitlab()` function that makes it easy to do I think it would be useful.

**Comment by surmann** [comment]
Thanks for your answer. I would like to submit something, to use gitlab with covr.

I worked on the yaml file for gitlab. [Here](https://gitlab.com/surmann/ODEnetwork) is an example. I just copied one of my projects and add a yaml with focus on code coverage. It works fine. More or less. Take a look at the [Result](https://surmann.gitlab.io/ODEnetwork/coverage.html). Unfortunately, the report messes up, and I have no glue why.

Do you have an idea?

If you like to test something I can give you write access to this repo.

**Comment by surmann** [comment]
You can download the results from `covr` using artifacts within Gitlab. [Here](https://gitlab.com/surmann/ODEnetwork/pipelines) is the link to the pipeline. On the right is a button to download the artifacts. They show the same issue on the local machine. When I execute the `covr` code locally which I use in the [yaml](https://gitlab.com/surmann/ODEnetwork/blob/master/.gitlab-ci.yml) everything is fine.

What do you think?

**Comment by surmann** [comment]
@jimhester 
I updated the installation of `covr` to the current github version. Unfortunately, the result looks still ugly. Do you have any hints how to work out the reason?

**Comment by jimhester** [comment]
The css and javascript dependencies are not being loaded, it looks like because GitLab is serving them with the wrong mime types. e.g. this is what I get in the chrome dev console.

> Refused to apply style from 'https://surmann.gitlab.io/ODEnetwork/lib/datatables-css-0.0.0/datatables-crosstalk.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

> Refused to execute script from 'https://surmann.gitlab.io/ODEnetwork/lib/htmlwidgets-1.2/htmlwidgets.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

The css should be served with a mime type of 'text/css' and the javascript something like 'application/javascript'.

I don't know how you would configure GitLab to serve these correctly, or if it is even possible.

**Comment by surmann** [comment]
I am surprised that I can observe the same issue after downloading the artifacts. Hence, I think something is wrong in the file itsself. Comparing an html file from a local coverage report to the one from GitLab shows different file. Unfortunately, I don't know how to interpret the difference.

GitLab supports most mime types, as they mention in the help:
https://help.github.com/articles/mime-types-on-github-pages/

Does it make sense to take a look at the differences in the html file? Or which way would you go @jimhester ?

**Comment by surmann** [comment]
I found the error. Mea culpa!
I copied the dependencies and removed the directory "lib".

Sorry for that.

**Comment by overmar** [comment]
Could the function return the coverage rather than TRUE from file.copy? It would save having to rerun package_coverage to get the percentage
