### ISSUE TITLE
covr causing failed TravisCI builds?

### ISSUE THREAD

**Issue by billdenney** [r-lib/covr#334]
In the past couple of days, I've had failed builds on TravisCI through what appears to be it waiting on covr() to return:

https://travis-ci.org/billdenney/pknca/jobs/431929216

The main package is here: https://github.com/billdenney/pknca

Is there a way to fire-and-forget the covr() call after a successful TravisCI build so that it becomes only the responsibility of codecov.io at that point?

**Comment by billdenney** [comment]
A subsequent build yielded this message during the `covr()` run:

```
Error: Failure in `/tmp/RtmpXtetLQ/R_LIBS30cf80d11a9/PKNCA/PKNCA-tests/testthat.Rout.fail`
Execution halted
Warning message:
system call failed: Cannot allocate memory 
```

https://travis-ci.org/billdenney/pknca/jobs/431938785

**Comment by jimhester** [comment]
You will have to try and debug this locally first with package_coverage()

**Comment by billdenney** [comment]
`package_coverage()` locally (Windows 10) gives no issues:

```
> library(covr)
> foo <- package_coverage()
> print(foo)
PKNCA Coverage: 94.19%
R/class-general.R: 73.81%
R/class-PKNCAresults.R: 79.63%
R/tss.stepwise.linear.R: 87.72%
R/class-PKNCAconc.R: 88.24%
R/tss.R: 88.68%
R/class-PKNCAdata.R: 89.15%
R/tss.monoexponential.R: 89.47%
R/pk.calc.all.R: 90.88%
R/exclude_nca.R: 92.41%
R/class-PKNCAdose.R: 93.80%
R/check.intervals.R: 95.88%
R/interpolate.conc.R: 96.55%
R/001-add.interval.col.R: 96.92%
R/superposition.R: 97.48%
R/parseFormula.R: 97.70%
R/pk.calc.simple.R: 97.93%
R/PKNCA.options.R: 98.84%
R/general.functions.R: 99.12%
R/002-pk.business.rules.R: 100.00%
R/AIC.list.R: 100.00%
R/auc.R: 100.00%
R/aucint.R: 100.00%
R/choose.intervals.R: 100.00%
R/cleaners.R: 100.00%
R/exclude.R: 100.00%
R/half.life.R: 100.00%
R/merge.R: 100.00%
R/pk.calc.c0.R: 100.00%
R/pk.calc.dn.R: 100.00%
R/pk.calc.urine.R: 100.00%
R/provenance.R: 100.00%
> 
```

**Comment by jimhester** [comment]
From your error messages it seems to be caused by using too much memory, I am not sure there is a lot that can be done about it. You could try running `package_coverage()` on travis first, then pass the result to codecov to see if it is failing when calculating coverage (which is likely) or when uploading the reports to codecov.

```r
Rscript -e 'cov <- covr::package_coverage()' -e 'print(cov)' -e 'covr::codecov(coverage = cov)'
```

**Comment by billdenney** [comment]
I'm still having trouble:  https://travis-ci.org/billdenney/pknca/jobs/432495895

When running locally, `package_coverage()` returns in about a minute.

**Comment by wlandau** [comment]
Whatever the issue may be, it seems like these builds started failing right after the latest CRAN release of covr. Could something have changed in how covr uses memory resources?

**Comment by jimhester** [comment]
Please try with the current devel version of covr, it may be https://github.com/r-lib/covr/issues/335 which is now fixed.

**Comment by wlandau** [comment]
Works for drake, thanks!

**Comment by billdenney** [comment]
Works for PKNCA, too.  Thanks!

**Comment by wlandau** [comment]
In that case, shall we close?

**Comment by billdenney** [comment]
I think yes.
