### ISSUE TITLE
Local and Travis coverage differ when testing `plot()`

### ISSUE THREAD

**Issue by echasnovski** [r-lib/covr#341]
Here is [a link](https://github.com/echasnovski/covrissue) to "reprackage".

More thorough description:

- I have defined several [functions involving `plot()`](https://github.com/echasnovski/covrissue/blob/master/R/plot-funs.R). I then [test them](https://github.com/echasnovski/covrissue/blob/master/tests/testthat/test-plot-funs.R) both using vdiffr (several approaches) and directly with `expect_silent()`.
- Files '.travis.yml' and 'codecov.yml' were created using `usethis::use_travis()` and `usethis::use_coverage()` repsectively. To track coverage on Travis I also added `- Rscript -e 'covr::package_coverage()'` at the end.

Locally there is 100% coverage (as it seems it should be), but at Travis all functions with `plot()` are [not covered](https://travis-ci.org/echasnovski/covrissue/builds/448535703).

I also tried using `echo 'covr::codecov()' | R --vanilla` as recommended in [this issue](https://github.com/r-lib/covr/issues/180). Result didn't change.

To test that coverage works on Travis, I also added [function without `plot()`](https://github.com/echasnovski/covrissue/blob/master/R/non-plot-funs.R) which is tested [in separate file](https://github.com/echasnovski/covrissue/blob/master/tests/testthat/test-non-plot-funs.R). It [gets covered](https://travis-ci.org/echasnovski/covrissue) and `plot()` ones still aren't.

Locally tried covr both versions from CRAN (3.2.1) and current GitHub master, which gave the same result:
![covrissue_local-coverage](https://user-images.githubusercontent.com/24854248/47874764-523dcd80-de1d-11e8-83bb-a1a260dab2f1.png)

**Comment by jimhester** [comment]
I believe this is because vdiffr requires a newer version of freetype (2.6.0) then is installed by default on travis, so the tests are being skipped.

@lionel- will know for sure, and can point you to what needs to the best way to ensure the correct version is installed.

**Comment by echasnovski** [comment]
Seems plausible as I just created a test for plotting function without vdiffr and it got covered on Travis.
Didn't know the functionality of skipping the whole test if there is no appropriate dependency. Is it testthat or vdiffr feature?

**Comment by lionel-** [comment]
yes the vdiffr on CRAN no longer works well. The dependency on system FreeType has been removed in the dev version. You need to add `Remotes: lionel-/vdiffr` to your DESCRIPTION file and regenerate all your figures.

I'll look into a vdiffr release in the coming month or two. In ggplot2 we added an indirection for `expect_doppelganger()` so it still works on CRAN: https://github.com/tidyverse/ggplot2/blob/master/tests/testthat/helper-vdiffr.R

**Comment by echasnovski** [comment]
Thank you both @jimhester and @lionel- .
