### ISSUE TITLE
Error in loadNamespace("DT") : there is no package called ‘DT’

### ISSUE THREAD

**Issue by ramiromagno** [r-lib/covr#343]
`covr::report()` gives me:

```R
Error in loadNamespace("DT") : there is no package called ‘DT’
```
should not the package DT be moved from the `Suggests` to the `Imports` section?

`covr` version is `3.2.1`.

**Comment by jimhester** [comment]
No, it is in suggests by design, you simply need to install it on your system.

**Comment by ramiromagno** [comment]
Thank you for your quick reply.

Would you mind explaining what you mean by _it is in suggest by design_?

**Comment by jimhester** [comment]
https://github.com/r-lib/covr/issues/53#issuecomment-87169597

previously shiny, and now DT is purposefully only in Suggests, because it is needed only when running `report()`, we don't want to install it when people are using covr on travis.

**Comment by ramiromagno** [comment]
hey @jimhester,

thank you for the explanation!
