### ISSUE TITLE
README badge coverage doesn't charge for `coveralls`

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/covr#344]
No matter what my code coverage is, I get the same code coverage value on `README` badge. Surprisingly, this is the case only for the `coveralls` badge, and not for the `codecov` badge.

For example, the [README](https://github.com/IndrajeetPatil/ggstatsplot/blob/master/README.md) shows the code coverage to be `37%`, while it is actually `89%` on the `coveralls.io` webpage-
 
![covr](https://user-images.githubusercontent.com/11330453/48681392-3867ee80-eb70-11e8-9a4f-e4b216824821.gif)

This is `.yml` file for `coveralls`:
https://github.com/IndrajeetPatil/ggstatsplot/blob/71346fbb6fef523a2ef252cdcf81890a8dfb9a41/.coveralls.yml#L1-L2

And the corresponding portion from `.travis.yml`
https://github.com/IndrajeetPatil/ggstatsplot/blob/71346fbb6fef523a2ef252cdcf81890a8dfb9a41/.travis.yml#L80-L84

What am I doing wrong?

P.S. In case you are wondering why I want to have separate badges for `codecov` and `coveralls`, I use one with `type = "all"` (so vignettes, examples, tests, etc.  included), while the other relies solely on tests.

**Comment by jimhester** [comment]
Looks like it is 89 now.

**Comment by IndrajeetPatil** [comment]
Huh, it is an issue with my browser. Microsoft Edge gives me a completely different view. This is weird.

**Comment by jimhester** [comment]
It is probably just the page cache in your browser.

**Comment by IndrajeetPatil** [comment]
Clearing the cache solved it. Thanks for your patience!
