### ISSUE TITLE
[QUESTION] Is something with "pkgnet" broken?

### ISSUE THREAD

**Issue by jameslamb** [r-lib/covr#353]
Hey @jimhester . I'm one of the maintainers of [pkgnet](https://github.com/UptakeOpenSource/pkgnet). I came to the `covr` repo tonight and was clicking around looking for something, and was surprised to see that we showed up in some of your documentation!

What does [this error in your revdep docs](https://github.com/r-lib/covr/blob/master/revdep/problems.md#pkgnet) mean? Is there something we could do to make it easier for you to test new versions of `covr` against our project?

Thanks!

**Comment by jimhester** [comment]
That is the reverse dependency results of covr from the last time I did a CRAN submission. It looks like there was an issue installing `data.table` when I did the checks, however it is likely just a spurious issue, probably nothing that you or the data.table maintainers need to be concerned about, I don't think there is any issue.

**Comment by jameslamb** [comment]
Ok sounds good, thanks!
