### ISSUE TITLE
covr:: report() and package_coverage() fails every where.

### ISSUE THREAD

**Issue by Amitav507** [r-lib/covr#354]
`library(covr)`
`setwd("C:/Users/User/Documents/R/win-library/3.5/dplyr")`
`cov<-package_coverage()`

returns

> Error in file(con, "r") : cannot open the connection
In addition: Warning messages:
1: In utils::install.packages(repos = NULL, lib = tmp_lib, pkg$path,  :
  installation of package ‘C:/Users/User/Documents/R/win-library/3.5/dplyr’ had non-zero exit status
2: In file(con, "r") :
  cannot open file 'C:/Users/User/AppData/Local/Temp/Rtmpe8y0Rb/R_LIBS155c766f186e/dplyr/R/dplyr': No such file or directory

**Comment by kenahoo** [comment]
This is my experience lately too - I can't get `covr::report()` to run anymore, where previously (a few months ago?) it ran fine.

For example, using R 3.6.0 and running `covr` version 3.2.1 on the latest Github checkout of `covr`'s own `master` branch:

```
[~/git-foreign/covr] [master] % Rscript -e 'covr::report()'                                                                                                    
Error: Failure in `/private/var/folders/zp/hj5hqfw970z0_78mrb_802lm0001z9/T/RtmpklkE8k/R_LIBS11ec325cb0a17/covr/covr-tests/testthat.Rout.fail`
Execution halted

[~/git-foreign/covr] [master] % ls /private/var/folders/zp/hj5hqfw970z0_78mrb_802lm0001z9/T/RtmpklkE8k/R_LIBS11ec325cb0a17/covr/covr-tests/testthat.Rout.fail
ls: /private/var/folders/zp/hj5hqfw970z0_78mrb_802lm0001z9/T/RtmpklkE8k/R_LIBS11ec325cb0a17/covr/covr-tests/testthat.Rout.fail: No such file or directory
```

Same thing happens if I load the local Git `master` branch:

```
[~/git-foreign/covr] [master] % git log -n1 --date=rfc
commit e344676bddd3a1cf1f5388a4d32dbd5e792b426a (HEAD -> master, origin/master, origin/HEAD)
Author: Jim Hester <james.f.hester@gmail.com>
Date:   Mon, 10 Jun 2019 08:21:02 -0400

    Define flags for C++14+
    
    Fixes #369

[~/git-foreign/covr] [master] % Rscript -e 'devtools::load_all(); covr::report()'        
Loading covr
Error: Failure in `/private/var/folders/zp/hj5hqfw970z0_78mrb_802lm0001z9/T/Rtmpd2SeZa/R_LIBS1206f7a381c4d/covr/covr-tests/testthat.Rout.fail`
Execution halted
```

Suggestions on troubleshooting?

**Comment by jimhester** [comment]
You can get verbose output from 

`covr::package_coverage(quiet = FALSE, clean = FALSE)`

Then look in `tempdir()` to inspect the files.

**Comment by kenahoo** [comment]
As an experiment, I did the following:

  * installed `covr` 3.2.0, ran `Rscript -e 'covr::report()'`.  Failed with the same error.
  * installed `covr` 3.1.0, ran `Rscript -e 'covr::report()'`.  Failed with this more verbose error:

```
[~/git-foreign/covr] [master] % Rscript -e 'covr::report()'                                                                                                    
Error: Failure in `/private/var/folders/zp/hj5hqfw970z0_78mrb_802lm0001z9/T/RtmpgdIDeL/R_LIBS1238a7b7a319c/covr/covr-tests/testthat.Rout.fail`
> ops <- options("crayon.enabled" = FALSE, warn = 1)
> library(testthat)
> library("covr")
Error in parse(text = trace_dir) : <text>:1:1: unexpected '/'
1: /
    ^
Error: package or namespace load failed for ‘covr’:
 unable to load R code in package ‘covr’
Execution halted
Error in parse(text = trace_dir) : <text>:1:1: unexpected '/'
1: /
    ^
Error: unable to load R code in package ‘covr’
Execution halted
```

* Looked like a problem with the codebase I was trying to do coverage testing on (`covr` itself), so I switched back to my own internal package.  `Rscript -e 'covr::report()'` now ran successfully.

* Tried upgrading to `covr` 3.2.0 and 3.2.1, which both now ran successfully.

My theory: the old versions of `covr` succeeded at something (maybe creating a directory, installing a package?) that the new version didn't, and that enabled the new version of `covr` to succeed afterwards.  Will keep digging.

**Comment by kenahoo** [comment]
In the environment (a Docker image) where coverage is still failing, I got more verbose output by doing this:

```
% Rscript -e 'covr::report(covr::package_coverage(quiet=FALSE), file="artifacts/coverage/index.html")'
Warning: unknown option '--with-keep.parse.data'
* installing *source* package 'AMGUtils' ...
** libs
g++ -m64  -I"/usr/include/R" -DNDEBUG  -I"/usr/lib64/R/library/Rcpp/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -O0 --coverage -c window.cpp -o window.o
In file included from /usr/include/c++/4.8.2/x86_64-redhat-linux/bits/os_defines.h:39:0,
                 from /usr/include/c++/4.8.2/x86_64-redhat-linux/bits/c++config.h:2097,
                 from /usr/include/c++/4.8.2/cmath:41,
                 from /usr/lib64/R/library/Rcpp/include/Rcpp/platform/compiler.h:100,
                 from /usr/lib64/R/library/Rcpp/include/Rcpp/r/headers.h:59,
                 from /usr/lib64/R/library/Rcpp/include/RcppCommon.h:29,
                 from /usr/lib64/R/library/Rcpp/include/Rcpp.h:27,
                 from window.cpp:1:
/usr/include/features.h:330:4: warning: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Wcpp]
 #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
    ^
g++ -m64 -shared -L/usr/lib64/R/lib -Wl,-z,relro --coverage -o AMGUtils.so window.o -L/usr/lib64/R/lib -lR
installing to /tmp/RtmpVcjsOy/R_LIBS122b575ce892/AMGUtils/libs
** R
** inst
** tests
** byte-compile and prepare package for lazy loading
** help
No man pages found in package  'AMGUtils' 
*** installing help indices
Warning in file.copy(file.path(R.home("doc"), "html", "R.css"), outman) :
  problem copying /usr/share/doc/R-3.5.0/html/R.css to /tmp/RtmpVcjsOy/R_LIBS122b575ce892/AMGUtils/html/R.css: No such file or directory
** building package indices
** testing if installed package can be loaded
Error: package or namespace load failed for 'AMGUtils' in namespaceExport(ns, exports):
 undefined exports: downsampleForPlot
Error: loading failed
Execution halted
ERROR: loading failed
* removing '/tmp/RtmpVcjsOy/R_LIBS122b575ce892/AMGUtils'
Error in file(con, "r") : cannot open the connection
Calls: <Anonymous> ... as.data.frame -> <Anonymous> -> add_hooks -> readLines -> file
In addition: Warning messages:
1: In utils::install.packages(repos = NULL, lib = tmp_lib, pkg$path,  :
  installation of package '/tmp/AMGUtils' had non-zero exit status
2: In file(con, "r") :
  cannot open file '/tmp/RtmpVcjsOy/R_LIBS122b575ce892/AMGUtils/R/AMGUtils': No such file or directory
Execution halted
```

It's failing to install the package being tested, because it's failing to find an `Rcpp` based function called `downsampleForPlot`.  This is odd, because `R CMD check` and all the unit tests succeed on this package.

**Comment by kenahoo** [comment]
Figured out what's going on here.  The generated files `R/RcppExports.R` and `src/RcppExports.cpp` had not yet been generated.  As soon as I generate them, all subsequent runs of `covr` succeed.  

So I think I have 2 questions:

1) Could `quiet=FALSE` become the default?  My coverage tests are typically run in CI/CD, where I don't have much ability to debug.  In this case I had to pull new copies of Docker environments and try to replicate in there, which is pretty awkward, before I could figure out what's going on.  Having verbose error messages would have helped a lot.

I can easily work around this by running `Rscript -e 'covr::report(covr::package_coverage(quiet=FALSE), file="artifacts/coverage/index.html")'` in my coverage runner script, of course.

2) Did a previous version of `covr` do any "building" of the package, e.g. running `Rcpp::compileAttributes()` or `devtools::build(path='.')` or similar?  Or did I usually just get lucky and the package was in a more "built" state when I used to run?  Right now I'm trying to script this for CI/CD, most of my previous coverage runs have been in RStudio, where it probably was generating those files in the background without me noticing.

**Comment by jimhester** [comment]
No, `quiet = FALSE` cannot become the default, most of the time it is unnecessary output.

covr has never done any additional building of the package, it simply runs `utils::install.packages(repos = NULL)` on your package directory.

**Comment by kenahoo** [comment]
Then is there some way for it to report more useful information when a failure happens?  All it says right now is basically a verbose version of "it failed":

```
% Rscript -e 'covr::report()'                 
Error in file(con, "r") : cannot open the connection
Calls: <Anonymous> ... %||% -> package_coverage -> add_hooks -> readLines -> file
In addition: Warning messages:
1: In utils::install.packages(repos = NULL, lib = tmp_lib, pkg$path,  :
  installation of package ‘/Users/kwilliams/git/amgutils’ had non-zero exit status
2: In file(con, "r") :
  cannot open file '/private/var/folders/zp/hj5hqfw970z0_78mrb_802lm0001z9/T/Rtmp4wi0vO/R_LIBS3a8b7c90b968/AMGUtils/R/AMGUtils': No such file or directory
Execution halted
```

In the CI/CD case, when this is happening on a remote machine, it can be very difficult to know where to start.

One improvement would be to check whether the `install.packages(...)` call in `package_coverage()` succeeded or not, and report the relevant error if it didn't.  Right now it continues running and eventually dies when it can't find some files it expected to be created.

**Comment by jimhester** [comment]
There is not a way to check if the `install.packages()` call succeeded, it only returns warnings in many failure cases, but some of the warnings are false positives and not actual failures.

**Comment by kenahoo** [comment]
It should be possible to check whether the package is actually installed after the command is run, though, right?

**Comment by kenahoo** [comment]
Since this ticket is still open, I'm adding another similar experience - another CI/CD run failed today with this output:

```
$ Rscript -e 'covr::report(file="artifacts/coverage/report.html")'
Error in file(con, "r") : cannot open the connection
Calls: <Anonymous> ... as.data.frame -> package_coverage -> add_hooks -> readLines -> file
In addition: Warning messages:
1: In utils::install.packages(repos = NULL, lib = tmp_lib, pkg$path,  :
  installation of package '/builds/internal/amg/Foo' had non-zero exit status
2: In file(con, "r") :
  cannot open file '/tmp/Rtmptdm6g1/R_LIBS4b4135ba3bd/Foo/R/Foo': No such file or directory
Execution halted
ERROR: Job failed: exit code 1
```

This time I can't seem to reproduce the failure by doing a manual run in the same Docker image, so I'm at a dead end unless I start modifying the CI/CD code itself to be more verbose while running on the remote machine.

Would you be receptive to a patch that tries to give more helpful output in the failure cases?

**Comment by nalzok** [comment]
Hi @kenahoo, I'm facing the same problem.

> Figured out what's going on here. The generated files `R/RcppExports.R` and `src/RcppExports.cpp` had not yet been generated. As soon as I generate them, all subsequent runs of `covr` succeed.

Can you elaborate on how to generate these files? I want to know the coverage of a package that I'm going to maintain, but I'm not familiar with `RCpp` and package building.

**Comment by kenahoo** [comment]
Hi @nalzok, in my case I just needed to run `devtools::build(path='.')` in order to do all the necessary building steps.

**Comment by nalzok** [comment]
Thanks, @kenahoo! Unfortunately, it doesn't work for me, as the `RcppExports` files in my project aren't produced by an automated process. Instead, they appear to be handwritten by my predecessor, and I definitely don't want to break it.

*Chuckles* I'm in danger.
