### ISSUE TITLE
Unhelpful error message

### ISSUE THREAD

**Issue by gustavdelius** [r-lib/covr#355]
When I run package_coverage() on my package I get the error message:

> Error: Failure in `/tmp/RtmpNuIBTn/R_LIBS730251fdaab7/mizer/mizer-tests/testthat.Rout.fail`

That temporary file is immediately deleted, so I have no way of finding out what caused the error. The package builds and tests fine. Is there some way for me to track down the error?

**Comment by jimhester** [comment]
Use `package_coverage(clean = FALSE)`.
