### ISSUE TITLE
Not counting lines properly in function factories

### ISSUE THREAD

**Issue by ramiromagno** [r-lib/covr#363]
It seems `covr` is not using the same approach for functions within functions.

Here's an example:

![snap](https://user-images.githubusercontent.com/19862384/56855481-b6120080-693f-11e9-99d3-8a61bf06045a.png)

`covr` is counting lines 6 and 9 as not tested when in reality they are.

**Comment by jimhester** [comment]
covr tracks coverage of code run during the tests. The lines you reference you are likely run when the package is installed or possibly on package loading, not during the tests, unless you are calling `endofunction2()` during your tests.

This is working as expected.

**Comment by ramiromagno** [comment]
I am calling `endofunction2()` indirectly during the tests.

For example, `endofunction2()` is part of a method definition for the generic `union()`:

https://github.com/ramiromagno/gwasrapidd/blob/514d069b1ed242ebbd67b46f11369b3b79e68f1e/R/generics.R#L70-L72
```R
setMethod("union",
          signature = c(x = "studies", y = "studies"),
          definition = endofunction2(dplyr::union, "studies"))
```
`union()` is then tested:

https://github.com/ramiromagno/gwasrapidd/blob/514d069b1ed242ebbd67b46f11369b3b79e68f1e/tests/testthat/test-generics.R#L210-L220

```R
with_mock_api({
  test_that("set operations on S4 studies", {
    s1 <- get_studies(study_id = 'GCST001085')
    s2 <- get_studies(study_id = 'GCST000392')
    s3 <- get_studies(study_id = c('GCST001085', 'GCST000392'))
    expect_is(s1, 'studies')
    expect_is(s2, 'studies')
    expect_is(s3, 'studies')
    # union
    expect_identical(union(s1, s2), s3)
    expect_identical(union(s3, s3), s3)
```

So I don't think this is working as expected.

**Comment by jimhester** [comment]
No, you are not calling them during the tests, `setMethod` is being called when the package is installed.

**Comment by ramiromagno** [comment]
ok, I am confused. So, lines 7 and 8, that are called 40x, are being called when/where?

**Comment by jimhester** [comment]
7, 8 are being called in your tests, but 6 and 9 are being called when the package is installed.

An example which hopefully demonstrates what is going on follows.

First, source file ''power.R", which defines a functional `pow` and a function `pow_2` built from it.

```r
# power.R
pow <- function(power) {
  force(power)

  function(x) {
    x ^ power
  }
}

pow_2 <- pow(2)
```

Then a test file which checks that pow_2 works as expected.

```r
# tests.R
library(testthat)

expect_equal(pow_2(5), 5^2)
```

Now we can run covr on these with `file_coverage()`.

```r
cov <- as.data.frame(covr::file_coverage("power.R", "tests.R"))

cov[c("filename", "functions", "first_line", "value")]
#>   filename functions first_line value
#> 1  power.R       pow          2     0
#> 2  power.R       pow          4     0
#> 3  power.R     pow_2          5     1
```

Note the only line which is covered is the inner function, as that is the only one which is actually run when running 'tests.R'. the other lines are run when running 'power.R', not 'tests.R'.

**Comment by ramiromagno** [comment]
@jimhester Thanks for the explanation and code! I get it now.

So for an R package with code like this, it's essentially impossible to get 100% coverage?

**Comment by jimhester** [comment]
You can use `#nocov` comments to exclude the lines if you want, but generally I would not worry all that much about %100 coverage in this case.

**Comment by ramiromagno** [comment]
Again, thanks for explaining all this!
