### ISSUE TITLE
Is there a way to cover code in `local({})`?

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/covr#366]
covr seems to skip these blocks currently. What would it take to support them?

**Comment by jimhester** [comment]
This is https://github.com/r-lib/covr/issues/113, it would require recursively descending into all objects in the package namespace, which I have so far resisted doing.

It would simplify the code in some cases, but I worry about the performance implications.

**Comment by gaborcsardi** [comment]
How about a marker to force-descend into a list or env?

**Comment by gaborcsardi** [comment]
OK, I'll close this and move to #113.
