### ISSUE TITLE
how to make work on travis?

### ISSUE THREAD

**Issue by jpritikin** [r-lib/covr#368]
I'm using `Rscript -e 'covr::codecov()'` but it isn't working. I get,

```
Still running (1 of 40): Rscript -e covr::codecov()

[31;1mThe command Rscript -e covr::codecov() exited with 1.[0m

[32;1mLog:[0m

Error in file(con, "r") : cannot open the connection
Calls: <Anonymous> -> package_coverage -> add_hooks -> readLines -> file
In addition: Warning messages:
1: In utils::install.packages(repos = NULL, lib = tmp_lib, pkg$path,  :
  installation of package â€˜/home/travis/build/OpenMx/OpenMxâ€™ had non-zero exit status
2: In file(con, "r") :
  cannot open file '/tmp/Rtmp5ghStb/R_LIBS37bd3e33f958/OpenMx/R/OpenMx': No such file or directory
Execution halted
```

Any idea how to fix it? I've tried running covr locally and it works fine.

[travis log](https://travis-ci.org/OpenMx/OpenMx/jobs/542663707)

**Comment by jimhester** [comment]
Did you try running `covr::package_coverage()` on your package locally? it looks to me like there are issues installing the package.

**Comment by jpritikin** [comment]
> Did you try running covr::package_coverage() on your package locally?

Yes, that's the first thing I tried. It works locally.

**Comment by jimhester** [comment]
You will need to try running `covr::package_coverage(quiet = FALSE)` on travis to see what the error is, I would guess it is an issue with using the updated compiler.

**Comment by jpritikin** [comment]
Hm, why would `omxSymbolTable.h` not be included? Which tarball is covr trying to build? Can we do `tar ztf build/OpenMx_*.tar.gz` to see what is in the tar file?

```
 installing *source* package ‘OpenMx’ ...
** using staged installation
NOTE: ./.devmode exists; will enable extra compiler diagnostics
NOTE: ./configure is not an autoconf generated script.
Change default C/C++ compiler and default compile flags by editing ~/.R/Makevars
sha1sum libnpsol.a => 947c218861254b5737a91c61c8d8ed82684e413f   # GOOD
** libs
make: *** No rule to make target 'omxSymbolTable.h', needed by 'Compute.o'.  Stop.
ERROR: compilation failed for package ‘OpenMx’
* removing ‘/tmp/Rtmp32qB6L/R_LIBS379162b4a24e/OpenMx’
```

**Comment by jimhester** [comment]
I get the same error running `R CMD INSTALL OpenMx`. covr doesn't use a built tarball, it installs the package from the source tree directly. If your package cannot do this then it is not going to work.

**Comment by jpritikin** [comment]
Does covr do any kind of `make clean` or `git reset --hard`? If I leave the source tree in a buildable state then it should work?

**Comment by jimhester** [comment]
It pretty much just runs the equivalent of `R CMD INSTALL`

**Comment by jpritikin** [comment]
Looks like I figured out how to solve it, [https://travis-ci.org/OpenMx/OpenMx/jobs/542889371](https://travis-ci.org/OpenMx/OpenMx/jobs/542889371)

**Comment by jpritikin** [comment]
Thanks for your help!

**Comment by jpritikin** [comment]
Hm, why isn't covr picking up on the example code in manual pages? See [https://codecov.io/gh/OpenMx/OpenMx](https://codecov.io/gh/OpenMx/OpenMx)

**Comment by jpritikin** [comment]
Nevermind. I see I need to pass `type=c('tests','examples')`
