### ISSUE TITLE
roxygen2

### ISSUE THREAD

**Issue by jpritikin** [r-lib/covr#371]
roxygen2 needs to compile all the objects and then covr needs to recompile them. This results in the need to recompile everything twice. Would it be possible to compile the objects for covr, run roxygen2 to generate the man pages, then run covr on the examples?

**Comment by jimhester** [comment]
Sure, it is possible, but it is not something that I am going to support in covr itself. You should be able to run something like the following to compile the shared library with the necessary flags to track coverage.

```r
withr::with_makevars(getOption("covr.flags"), assignment = "+=",
  utils::install.packages(
    ".",
    repos = NULL,
    type = "source",
    INSTALL_opts = c("--example",  "--install-tests", "--with-keep.source",
      "--with-keep.parse.data", "--no-multiarch")
  )
)
```

**Comment by jpritikin** [comment]
I notice that gcc is invoked with `-O2  -O0`. Does the `-O0` take precedence?

**Comment by jpritikin** [comment]
> Sure, it is possible

This worked. Thanks.
