### ISSUE TITLE
return overall percentage of coverage from covr::codecov

### ISSUE THREAD

**Issue by jpritikin** [r-lib/covr#372]
Can `covr::codecov` return the % coverage across all files? If not, can I get this info some other way?

**Comment by jimhester** [comment]
```r
cov <- covr::package_coverage()
# Use the default print method, or do whatever you want with the cov object.
cov

covr::codecov(coverage = cov)
```

**Comment by jimhester** [comment]
There is also a `quiet` arg to codecov, that print the coverage object by default.

**Comment by jpritikin** [comment]
I used,

```
cov <- covr::package_coverage()
pct <- percent_coverage(cov)
```
However, this did not match codecov. I got [56.7](https://travis-ci.org/OpenMx/OpenMx/jobs/547865979) on travis but codecov shows [46.16](https://codecov.io/gh/OpenMx/OpenMx/commit/6b94821c7e111cef778d01f2443101c8fcc58863). Am I using the wrong API?

**Comment by jpritikin** [comment]
Hm, looks like `percent_coverage` does not include C++ files. How to include everything?

**Comment by jpritikin** [comment]
Any progress here? I also posted, https://community.rstudio.com/t/return-overall-percentage-of-coverage-from-covr-codecov/33588/2
