### ISSUE TITLE
how to avoid compiling everything twice?

### ISSUE THREAD

**Issue by jpritikin** [r-lib/covr#373]
I thought we had this solved, but I guess [not](https://travis-ci.org/OpenMx/OpenMx/jobs/548000650). What condition is checked to decide whether to recompile?

**Comment by jimhester** [comment]
This sort of question is a better fit for <https://community.rstudio.com>. Do you mind asking it over there? (You might want to read <https://www.tidyverse.org/help/> first to maximise your chances of getting a good answer)
