### ISSUE TITLE
return overall percentage of coverage from covr::codecov 

### ISSUE THREAD

**Issue by jpritikin** [r-lib/covr#374]
I used,

```
cov <- covr::package_coverage()
pct <- percent_coverage(cov)
```

However, this did not match codecov. I got 56.7 on travis but codecov shows 46.16. Am I using the wrong API? Hm, looks like `percent_coverage` does not include C++ files. How to include everything?

**Comment by jimhester** [comment]
codecov is reporting coverage per line, covr is reporting coverage per expression. See `?tally_coverage`.

Also please consider opening these issues at <https://community.rstudio.com>, the issue tracker is not for general help.
