### ISSUE TITLE
Internal functions used purely to construct global package variables are not covered

### ISSUE THREAD

**Issue by dirkschumacher** [r-lib/covr#386]
Let's say you have a package with a global package variable. This global variable is populated using an internal package function. This function is only called to construct that internal global variable.

When I run `covr` it reports that the internal function is not covered by any test. Which is true, it is not called during the test, but it must have been called at some point to create the global variable.

Hope this makes sense. I am not sure if that can even be resolved.

In the example below, the internal function is not covered by the test. Although it must have been called at some point.

``` r
covr::code_coverage(
  "interal_fun <- function(x) {
    x
   }
   global_variable <- interal_fun(5)
   public_fun <- function() global_variable
  ",
  "public_fun()"
)
#> Coverage: 50.00%
#> /var/folders/mz/g_202xxj32b6r__57x3dmfkr0000gn/T//Rtmp083NfR/source.R131b0755963c1: 50.00%
```

<sup>Created on 2019-08-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jimhester** [comment]
This is expected, covr only records files that are run during the tests, not during build / install time.

I would suggest you just use `#nocov start`, `#nocov end` blocks around this code. (https://github.com/r-lib/covr#exclusion-comments)

**Comment by dirkschumacher** [comment]
Ah thanks a lot! Will do that then.
