### ISSUE TITLE
Vulnerability with the bootstrap version

### ISSUE THREAD

**Issue by stepintooracledba** [r-lib/covr#397]
Hi Team,

Looks like covr still uses older version of bootstrap which has below vulnerability.

XSS is possible in the collapse data-parent attribute.

Can we get the latest version of bootstrap updated?

**Comment by jimhester** [comment]
The only place bootstrap is used in covr is to generate the interactive reports, which are run by the developer directly. In addition this is all coming from the DT package and its dependencies, not covr directly, there is nothing we can do in covr to change this.
