### ISSUE TITLE
coverage fails due to S3 method dispatching

### ISSUE THREAD

**Issue by hongyuanjia** [r-lib/covr#398]
I encountered a problem that `devtools::test()` runs successfully but `covr::codecov()` doesn't.

All failures are related to S3 dispatching, specifically [`$.Idf`](https://github.com/hongyuanjia/eplusr/blob/59a3140224b254f64098b52f60e038009d9b74dd/R/idf.R#L2800-L2823), [`$.Idd`](https://github.com/hongyuanjia/eplusr/blob/59a3140224b254f64098b52f60e038009d9b74dd/R/idd.R#L571-L586). I have confirmed that all S3 methods are properly exported. So this issue is different with #362.

Below is part of the error message. Here `Idf` is an R6 object, and `Material` is an active binding. `Idf$Material` works fine in `devtools::test()` and in [CRAN](https://cran.r-project.org/package=eplusr) version of the package, but did not work in `covr::codecov()`. I expect `Idf$Material` returns the active binding directly but the error message indicated that somehow `$.Idf` has been replaced by a combination of `$.Idf` and [`$<-.Idf`](https://github.com/hongyuanjia/eplusr/blob/59a3140224b254f64098b52f60e038009d9b74dd/R/idf.R#L2849-L2878).

```r
covr::codecov(clean = FALSE, quiet = FALSE)

`class` should be a character vector.
1: paste0(idf$Material[[1]]$name(), ";") at testthat/test_impl-idf.R:941
2: idf$Material
3: `$.Idf`(idf, Material)
4: NextMethod()
5: (function (value) 
   {
       if (TRUE) 
           "Material"
       if (if (TRUE) {
           covr:::count("idf.R:2627:17:2627:30:17:30:2627:2627")
           missing(value)
       }) {
           if (if (TRUE) {
               covr:::count("idf.R:2628:21:2628:46:21:46:2628:2628")
               self$is_valid_class(class)
           }) {
               if (TRUE) {
                   covr:::count("idf.R:2629:21:2629:56:21:56:20296:20296")
                   return(self$objects_in_class(class))
               }
           }
           else {
               if (TRUE) {
                   covr:::count("idf.R:2631:21:2631:32:21:32:20298:20298")
                   return(NULL)
               }
           }
       }
       if (TRUE) {
           covr:::count("idf.R:2635:13:2635:72:13:72:20302:20302")
           replace_objects_in_class(self, private, class, value, FALSE)
       }
   })()
6: self$is_valid_class(class)
7: idf_is_valid_class_name(self, private, class, all)
8: assert(is.character(class), msg = "`class` should be a character vector.")
9: abort(err_type, msg)
```

**Comment by jimhester** [comment]
Sorry, your package is using too many non-standard features for me to invest the time necessary to debug the issue. If you would like this fixed you are going to have to invest the time yourself. I would suggest using `covr::package_coverage()` to debug locally.

**Comment by hongyuanjia** [comment]
I created a repo for reproduciblity. See [hongyuanjia/testcovr](https://github.com/hongyuanjia/testcovr).

Basically I want to add random active bindings to an R6 object.

### R6 definition

```r
A <- R6::R6Class("A", lock_objects = FALSE,
     public = list(
         initialize = function (x) {
             private$x <- x
         }
     ),
     private = list(
         x = NULL
     )
)
```

### Function factory

`factory()` returns a function that can be evaluated at the enclosing environment of an R6 object. The dirty part is `body(fun)[[2]][[3]] <- sym`. In order to avoid scoping issue, I directly insert the value of `sym` when `factory()` is called.

```r
factory <- function (r6, sym, value) {
    fun <- function (value) {
        sym <- sym
        if (missing(value) && sym != private$x) {
            private$x <- sym
        }
        private$x
    }
    environment(fun) <- r6$.__enclos_env__
    body(fun)[[2]][[3]] <- sym
    fun
}

a <- A$new("string")

factory(a, "y", value)
# function (value) 
# {
#     sym <- "y"
#     if (missing(value) && sym != private$x) {
#         private$x <- sym
#     }
#     private$x
# }
# <environment: 0x5614b4882f50>

factory(a, "y", value)()
# [1] "y"
```

### Add active bindings

```r
add_binding <- function (r6, sym) {
    makeActiveBinding(sym, factory(r6, sym, value), r6)
}

add_binding(a, "z")
a$z
# [1] "z"
```

Now everything works perfectly. The test package passes both `devtools::test()` and `rcmdcheck::rcmdcheck()`.

However, `covr::package_coverage()` failed. The error came from the line `sym <- "y"` in `factory(a, "y", value)`. Somehow, covr replace `sym <- "y"` with only `"y"`, which causes all lines below failed.

```r
Error: Failure in `/tmp/RtmpJoT4Bc/R_LIBS71a17de26d85/test/test-tests/test
that.Rout.fail`
(get_expr(quo), get_env(quo))
4: (function (value)
   {
       if (TRUE)
           "y"
       if (if (TRUE) {
           covr:::count("r6.R:17:13:17:46:13:46:19:19")
           missing(value) && sym != private$x
       }) {
           if (TRUE) {
               covr:::count("r6.R:18:13:18:28:13:28:20:20")
               private$x <- sym
           }
       }
       if (TRUE) {
           covr:::count("r6.R:20:9:20:17:9:17:22:22")
           private$x
       }
   })()

══ testthat results  ═══════════════════════════════════════════════════════════
[ OK: 0 | SKIPPED: 0 | WARNINGS: 0 | FAILED: 1 ]
1. Error: A (@test-r6.R#4)

Error: testthat unit tests failed
Execution halted
```

**Comment by jimhester** [comment]
The issue is in `body(fun)[[2]][[3]] <- sym`, covr modifies the function bodies to add the tracing code, so you are replacing a different part of the function than you expect. I see no easy way to remedy this.

**Comment by hongyuanjia** [comment]
For who may still be interested in this, here is the solution I found to make it work with covr.

Create the function manually using `eval(call("function", args, body), env)`, instead of modify its body after creation. Borrowed idea from from `pryr::make_function`

```r
factory <- function (r6, sym, value) {
    b <- as.call(list(
        quote(`{`),
        substitute(sym <- nm, list(nm = sym)),
        quote(
            if (missing(value) && sym != private$x) {
                private$x <- sym
            }
        ),
        quote(private$x)
    ))
    eval(call("function", as.pairlist(alist(value = )), b), r6$.__enclos_env__)
}
```

**Comment by nteetor** [comment]
I ran into a similar problem with {cascadess}. The problem has to do with a `print()` implementation. `devtools::test()` runs without issue, while covr functions fail. The error message suggests the print method is not found when covr runs the tests.
