### ISSUE TITLE
Keep LDFLAGS to link with external library

### ISSUE THREAD

**Issue by artemklevtsov** [r-lib/covr#399]
Hi,
How can I pass LDFLAGS to link package with an external shared library? Seem LDFLAGS from the `~/.R/Makevars` overwrites in the `.onLoad`.

**Comment by jimhester** [comment]
Set `options(covr.flags)` to whatever you need in addition to `--coverage`. But likely the package you are using should be searching the path to the shared library and setting it in the package `LDFLAGS`, not in your personal makevars file.

https://github.com/r-lib/covr/blob/47ab9bf4f4fdde431de8bf5b54b5757afa711abc/R/zzz.R#L10-L23
