### ISSUE TITLE
What should one do when tests take too much time

### ISSUE THREAD

**Issue by rafapereirabr** [r-lib/covr#402]
Hi all. This is more a of a question about best practices than a code issue. My team and I develop the [geobr](https://github.com/ipeaGIT/geobr) package to download geospatial data sets of Brazil. We have written some tests covering almost 70% of the package. The problem is that it there are too many tests and it takes lot of time to run all of them, so the package fails on **CRAN** submission and on **Travis** tests.

I've been using the arguments `skip_on_cran()` and `skip_on_travis()` but then **Codecov** does not capture correct  the coverage level of the package. Is there a best practice / recommendation on how one should deal with this ? 

ps. Thanks for your help in advance and congrats for developing such a great package!

**Comment by jimhester** [comment]
I think the best thing to do is split your tests into a set of unit tests that test small parts of your package and run quickly and one or more sets of integration tests that test larger swathes of code and are slower. 

Then you can use the unit tests on CRAN and run the sets of integration tests in separate travis jobs. 

You can use environment variables to control which tests run, either using `skip_if(Sys.getenv("TEST_ONE") != "")` in the test blocks individually or alternatively using a conditional in `testthat.R`, e.g. name the tests something like `test-unit-abc.R`, `test-integration1-xyz.R`, then run them with

```r
test_check(filter = "unit")
if (nzchar(Sys.getenv("TEST_ONE")) {
  test_check(filter = "integration1")
}
```

Then you can enable builds in your travis that just set the environment variables you need and run covr.

codecov.io will automatically merge coverage results from the same git commit, so your final coverage results will be the sum of all tests.

**Comment by rafapereirabr** [comment]
Thank you Jim. I'll will look further into your suggestion!
