### ISSUE TITLE
codecov doesn't work in Windows/GitHub Actions

### ISSUE THREAD

**Issue by randy3k** [r-lib/covr#406]
I have been playing with GitHub Actions with my package [collections](https://github.com/randy3k/collections) lately. I successfully deployed `covr::codecov` on [linux](https://github.com/randy3k/collections/runs/286094424) and [macOS](https://github.com/randy3k/collections/runs/286094479).

However, it didn't go nicely with [windows](https://github.com/randy3k/collections/runs/286094522). 
```
Run Rscript -e "covr::codecov()"
Error: Command '"C:\PROGRA~3\Chocolatey\bin\gcov.exe" "D:/a/collections/collections/src/dict.gcno" "-p" "-o" "D:/a/collections/collections/src"' failed (1)
Execution halted
```
I understand that my package contains c files so `gcov` is used to calcuate the coverage. Do I need to install additional software on the windows build?

**Comment by randy3k** [comment]
Fixed. It is just a matter of pointing to the correct path of `gcov`.

```
Rscript -e "options(covr.gcov = 'C:/Rtools/mingw_64/bin/gcov'); covr::codecov()"
```

**Comment by randy3k** [comment]
I was using my own way to install R on Windows/Github Actions. Future readers please use [rlib/actions/setup-r](https://github.com/r-lib/actions/blob/5a1d4947d033e6b101b74156b1a28cb7552cd5a9/setup-r/lib/installer.js#L247) and it automatically adds the PATH to `C:/Rtools/mingw_64/bin`.

**Comment by jimhester** [comment]
FWIW there is an example of using covr with GitHub actions at https://github.com/r-lib/actions/blob/c98787097a24a37568b0c9f78456788f90ea032c/examples/ci-full.yaml#L24-L28

**Comment by jimhester** [comment]
In general I don't think it is worth running covr on multiple OSs, unless you have OS specific code

**Comment by randy3k** [comment]
I get your point. I was just trying different setup.
