### ISSUE TITLE
package_coverage option to show time taken per test/example/vignette

### ISSUE THREAD

**Issue by jpritikin** [r-lib/covr#408]
Try to run covr on Travis is a nightmare. It keeps timing out and I have no idea why. [Example](https://travis-ci.org/OpenMx/OpenMx/jobs/608470710)

Is `testInstalledPackage` part of base R? What are the prospects of getting such an option added?

**Comment by jimhester** [comment]
It is part of the tools package, it is very unlikely to be updated and I certainly have no way to do so.

If you are trying to figure out if a certain test file is slow you can edit your `testthat.R` file to only run a portion of your tests. or use `file_coverage()` or `environment_coverage()` to run covr on specific files manually.

**Comment by jpritikin** [comment]
> If you are trying to figure out if a certain test file is slow you can edit your testthat.R file to only run a portion of your tests. or use file_coverage() or environment_coverage() to run covr on specific files manually.

This is impractical because Travis is so slow. It takes about 1 hour to try any change and get the results.

> It is part of the tools package, it is very unlikely to be updated and I certainly have no way to do so.

Would you be open to copying the code for `tools::testInstalledPackage` and modifying it to provide the sought diagnostic output?

**Comment by jimhester** [comment]
> Would you be open to copying the code for tools::testInstalledPackage and modifying it to provide the sought diagnostic output?

No
