### ISSUE TITLE
Cover code tested with `testthat::verify_output`

### ISSUE THREAD

**Issue by trevorld** [r-lib/covr#415]
It would be nice if `covr` would cover R package code being tested via `testthat::verify_output`.

**Comment by trevorld** [comment]
Actually, those lines seem to be covered just fine by ``covr`` when the tests are ran on either Travis-CI and/or Appveyor (but not locally on my machine).  There must be something wrong with my R installation?

**Comment by jimhester** [comment]
I would guess you have `skip_on_cran()` set for these tests. covr does not set `NOT_CRAN` for you, so you would have to do so yourself, e.g. with `withr::with_envvar(c(NOT_CRAN="true"), covr::package_coverage())` or similar

**Comment by trevorld** [comment]
Nope, no ``skip_on_cran()``.  The relevant test file only has ``expect_doppleganger`` (captured by ``covr`` both locally and on Travis-CI and/or Appveyor) and ``verify_output`` (not captured by ``covr`` locally but is captured on Travis-CI and/or Appveyor) statements and no skip statements at all.  Also, the tests are definitely run locally when I run ``devtools::test()`` (i.e. if I change one the expected test output it will give a test failure).  Locally ``covr::report`` seems to be capturing everything but the ``verify_output`` tests but my report on codecov seems to capture everything.

I'm using R version 3.6.1 (2019-07-05) on Ubuntu Linux and I've tried with both the latest release and development versions of ``covr``.  Maybe it is some subtle issue that may be resolved if I upgrade to R version 3.6.2?

As I said the report I get from ``codecov`` is correct and I can indirectly work from that.  Not sure how much time you should spend trying to figure out what is going on.

**Comment by trevorld** [comment]
Your instinct was correct, even though I never *explicitly* called a ``skip_on_cran()`` in my tests it seems that ``verify_output()`` *implicitly* does a ``skip_on_cran()`` on itself.  The following gives me the correct report:

    Sys.setenv(NOT_CRAN='true')
    covr::report()

Documentation from ``?verify_output``:

> On CRAN, ‘verify_output()’ will never fail, even if the output
     changes.
