### ISSUE TITLE
Testing function equality in a covr-compatible way?

### ISSUE THREAD

**Issue by jozefhajnala** [r-lib/covr#423]
Consider an R package with just 1 source file, say `hello.R` with the following content:

```r
hello <- function() "hi"
ciao <- function() "hi"
```

And a test file (e.g. using testthat it can look as follows):

```r
test_that(
  "Functions are identical",
  expect_identical(hello, ciao)
)
```

This test will pass running it with different methods (`tools::testInstalledPackage()` included).

However trying to compute the coverage using `covr::package_coverage(...)`, it will cause an error. Investigating by putting `dput(hello); dput(ciao)` in the test script, we can see from running `covr::package_coverage(...)`:

```
`hello` not identical to `ciao`.
target, current do not match when deparsed

function () 
{
    covr:::count("hello.R:1:10:1:24:10:24:3:3")
    "hi"
}
function () 
{
    covr:::count("hello.R:2:9:2:23:9:23:4:4")
    "hi"
}
```

So essentially is seems `covr` has put code inside the function bodies that makes them non-identical. Are there any best practices on how to prevent these issues when comparing functions as part of testing?

Thanks!

Some `sessionInfo()`:
- Using covr_3.5.0, R version 3.4.4 (2018-03-15), Platform: x86_64-pc-linux-gnu (64-bit), Running under: Ubuntu 18.04.1 LTS

**Comment by jimhester** [comment]
I would suggest not comparing function for equality during your tests, or skipping these particular tests when running under covr, e.g. `testthat::skip_if(in_covr())`
