### ISSUE TITLE
Export to_report_data()

### ISSUE THREAD

**Issue by melvidoni** [r-lib/covr#424]
This function can provide valuable information and prevent us from having to wrangle the data of the data frame, to obtain this summarised information. Could `to_report_data()` become an exported function?

**Comment by jimhester** [comment]
I don't think it needs to be exported, I would use `covr:::to_report_data()` if you really want it, or duplicate the logic in your own code.

**Comment by melvidoni** [comment]
I tried to do that. I called it with the result of `cover::package_coverage()`, but I get the following error: `in display_name(x) : inherits(x, "coverage") is not TRUE`

**Comment by melvidoni** [comment]
It worked, thank you!
