### ISSUE TITLE
Function Coverage doesn't work but File/Package do

### ISSUE THREAD

**Issue by skenkare6** [r-lib/covr#425]
I'm testing on Twitter's AnomalyDetection package and can get correct results for file and package coverage, but not function. Not sure if there's a bug or I'm using it incorrectly.

Here's my code:

```
setwd("AnomalyDetection")
library(devtools)
devtools::load_all(".")
library(testthat)
library(covr)
use_testthat()
use_test("test-ts.R")
test_file("tests/testthat/test-ts.R")
# This line works: 
# covr::file_coverage("R/ts_anom_detection.R", "tests/testthat/test-ts.R") 
# This line reports 0 percent:
covr::function_coverage("AnomalyDetectionTs")

```

**Comment by jimhester** [comment]
generally you should just use `covr::package_coverage()` if you are testing an R package.

```r
remotes::install_deps(dependencies = TRUE, upgrade = TRUE)
cov <- covr::package_coverage()
cov
covr::report(cov)
```

Also if you are using devtools you can use `devtools::test_coverage()` to run the coverage and produce the local report. If you really do want to use `function_coverage()` you need to give it code to run as well, but generally this is unneeded.
