### ISSUE TITLE
Cannot run covr::package_coverage, "make not found".

### ISSUE THREAD

**Issue by melvidoni** [r-lib/covr#429]
I was trying to run `covr::package_coverage` on the following repo: https://github.com/dankelley/oce

According to #252 I decided to run it with `quiet=FALSE` to diagnose the problem, and got the following error:

```
* installing *source* package 'oce' ...
** using non-staged installation
** libs
Warning in system(cmd) : 'make' not found
ERROR: compilation failed for package 'oce'
* removing 'C:/Users/path/AppData/Local/Temp/Rtmp0YlvEp/R_LIBS37dd4190562f/oce'
Error in file(con, "r") : cannot open the connection
In addition: Warning messages:
1: In utils::install.packages(repos = NULL, lib = tmp_lib, pkg$path,  :
  installation of package ‘myPath/packages/oce’ had non-zero exit status
2: In file(con, "r") :
  cannot open file 'C:/Users/path/AppData/Local/Temp/Rtmp0YlvEp/R_LIBS37dd4190562f/oce/R/oce': No such file or directory
```

I am running on Windows 10, and doing `devtools::test("path to ice here")` works perfectly, and all tests are run.

I have tried to:
  -  Manually update RTools,
  -  Restarting session
  - Updating R and restarting session
  - Checking that `find_rtools()` returns true.
  - Change the working directory to the package download path, and try to run covr there,
 
I am out of ideas, and weirdly enough, this happens in a bunch of packages (about 30 that I've tested), yet `covr` works like a charm in another bunch (about 90), with no extra effort. Same PC, same R installation.

**Comment by jimhester** [comment]
You need to have the buildtools on your system `PATH` in order to compile packages with compiled code.

Use `pkgbuild::with_build_tools(covr::package_coverage())`.

**Comment by melvidoni** [comment]
Thanks, _but sadly it didn't fix it_. `covr` sent another error, as follows:

```
collect2.exe: error: ld returned 1 exit status
no DLL was created
ERROR: compilation failed for package 'oce'
* removing 'C:/Users/path/AppData/Local/Temp/RtmpQFtDJ8/R_LIBS194c074573717/oce'
Error in file(con, "r") : cannot open the connection
In addition: Warning messages:
1: In utils::install.packages(repos = NULL, lib = tmp_lib, pkg$path,  :
  installation of package ‘myProject/oce’ had non-zero exit status
2: In file(con, "r") :
  cannot open file 'C:/Users/path/AppData/Local/Temp/RtmpQFtDJ8/R_LIBS194c074573717/oce/R/oce': No such file or directory
```

**Comment by moodymudskipper** [comment]
This did solve it for me FWIW, thanks.
