### ISSUE TITLE
How do I use codecov() with github actions?

### ISSUE THREAD

**Issue by hughjonesd** [r-lib/covr#430]
The NEWS says it is supported, but I am not smart enough to work it out without some documentation. E.g. maybe the README could have a section on it?

**Comment by jimhester** [comment]
https://github.com/r-lib/actions/tree/master/examples#test-coverage-workflow

**Comment by jucor** [comment]
Apologies if I'm a bit thick, but doesn't this example need to pass a repository-specific token to `codecov()` ?

**Comment by jimhester** [comment]
No, codecov automatically works without a token for public GitHub repositories. You only need a token if you have a private repository, and then you can add it as a secret to your GitHub Actions settings and pass it to R with something like `covr::codecov(token = "{{ secrets.CODECOV_TOKEN }}")`

**Comment by jucor** [comment]
Thanks a lot! This is magic :)

**Comment by jimhester** [comment]
It is briefly mentioned here https://docs.codecov.io/docs/frequently-asked-questions#where-is-the-repository-upload-token-found

**Comment by jucor** [comment]
Works like a charm :)

**Comment by Jeniffen** [comment]
> No, codecov automatically works without a token for public GitHub repositories. You only need a token if you have a private repository, and then you can add it as a secret to your GitHub Actions settings and pass it to R with something like `covr::codecov(token = "{{ secrets.CODECOV_TOKEN }}")`

@jimhester - that was super helpful! One thing I was still struggling with for a while, was a missing `$` sign. What worked for if someones is also trying to pass a token was :

```r
covr::codecov(token = "${{ secrets.CODECOV_TOKEN }}")
```

**Comment by gvegayon** [comment]
Just to complement, I have `codecov` working with GitHub Actions and Docker [here](https://github.com/USCbiostats/fmcmc/blob/2043b3a0db2e00283d764443513eb44a444994e0/.github/workflows/ci.yml) and it works OK! Not documented in `covr::codecov`, but as long as you pass the right envir variables, `covr` will do its magic:

```yml
      - name: Coverage
        env:
          MATNAME: ${{ matrix.name }}
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }} 
        run: |
          docker run --rm -i \
            -e MATNAME=$MATNAME \
            -e GITHUB_ACTION=$GITHUB_ACTION \
            -e GITHUB_REPOSITORY=$GITHUB_REPOSITORY \
            -e GITHUB_REF=$GITHUB_REF \
            -e GITHUB_HEAD_REF=$GITHUB_HEAD_REF \
            -e GITHUB_RUN_ID=$GITHUB_RUN_ID \
            -e GITHUB_SHA=$GITHUB_SHA \
            -e CODECOV_TOKEN=$CODECOV_TOKEN \
            -v ${PWD}:/mnt -w /mnt -e CI=true ${cntr} \
            ${{ matrix.cmd }} -e \
            '(v <- Sys.getenv("MATNAME"));if (v == "release") covr::codecov(quiet = FALSE)'
```

**Comment by edmondo1984** [comment]
I am trying to get the example working but this is failing for me with an error:

```
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck, covr
          needs: check

      - name: Test coverage
        run: covr::codecov()
        shell: Rscript {0}
```

This is the error, am I missing something?
```
Error: <callr_remote_error: Cannot install packages:
  * covr: dependencies must be TRUE, FALSE, NA or a list of dependency types>
   in process [96](https://github.com/.../runs/5605233986?check_suite_focus=true#step:6:96)28 
  -->
  <simpleError: Cannot install packages:
  * covr: dependencies must be TRUE, FALSE, NA or a list of dependency types>
  
   Stack trace:
  
   12. (function (...)  ...
   13. base:::withCallingHandlers(cli_message = function(msg) { ...
   14. get("lockfile_create_internal", asNamespace("pak"))(...)
   15. prop$stop_for_solution_error()
   16. private$plan$stop_for_solve_error()
   17. pkgdepends:::pkgplan_stop_for_solve_error(self, private)
   18. base:::stop("Cannot install packages:\n", msg, call. = FALSE)
   19. base:::.handleSimpleError(function (e)  ...
   20. h(simpleError(msg, call))
   21. base:::stop(e)
   22. (function (e)  ...
  
   x Cannot install packages:
  * covr: dependencies must be TRUE, FALSE, NA or a list of dependency types 
  
  Execution halted
  Error: Process completed with exit code 1.
```

**Comment by edmondo1984** [comment]
Any luck with private organizations?

```
Run covr::codecov(token = "***")
Request failed [404]. Retrying in 1.3 seconds...
Request failed [404]. Retrying in 1.3 seconds...
$detail
[1] "Could not find a repository associated with upload token ***"
```

**Comment by wlandau** [comment]
I am getting that same error with a public repo: https://github.com/wlandau/instantiate/actions/runs/5694415951/job/15435561221#step:7:68

**Comment by wlandau** [comment]
Seems to be fixed with a repo token, but I am surprised it was necessary for a public repo.
