### ISSUE TITLE
Codecov carry forward flags and skipped tests

### ISSUE THREAD

**Issue by Aariq** [r-lib/covr#432]
Now that Codecov has introduced "carry forward" flags, is there a possibility to not report test coverage of skipped tests?  (i.e. what was suggested in #58)  

I'm running tests that might occasionally fail if a web service is down, so I've decided to skip them if I can't ping the web service.  It would be nice if the coverage report could just be pulled from the previous commit with carry forward flags on codecov's end, but I don't think I can implement that unless `covr` doesn't report anything for those skipped tests.

**Comment by jimhester** [comment]
It might be possible, but I think it is unlikely to happen, I don't have the time or motivation to invest in this feature.

You could _probably_ do what you need by filtering the coverage data yourself before passing it to `covr::codecov()` however.

**Comment by Aariq** [comment]
Thanks!
