### ISSUE TITLE
Using covr in combination with withr::with_options may lead to problems

### ISSUE THREAD

**Issue by mb706** [r-lib/covr#434]
`covr` sets some options in `.onLoad` to default values. This can lead to problems when the package is loaded inside a `withr::with_options` call. E.g.
```r
# covr not loaded yet
withr::with_options(list("covr.exclude_start" = "#^"),  # disable exclude regions
  covr::file_coverage("<some R file>", "test.R")
)
```
No problems! However, `with_options` resets the `"covr.exclude_start"` option to `NULL` afterwards, so the following fails:
```r
covr::file_coverage("<some R file>", "test.R")
#> Error in regexpr(pattern = pattern, data, perl = TRUE, ...) : 
#>   invalid 'pattern' argument
```
(The workaround so far is obviously "load `covr` before `with_options`" or `unloadNamespace("covr")` afterwards)

**Comment by jimhester** [comment]
There isn't really any way to fix this...
