### ISSUE TITLE
package_coverage failing to install in tmp_dir in winos

### ISSUE THREAD

**Issue by yonicd** [r-lib/covr#443]
I have a package for example [{details}](https://github.com/yonicd/details)

that if I load the package then run `package_coverage` on winos it fails when it tries to install the package in tmp_dir

```r
library(details)
covr::package_coverage()
# Warning: package ‘details’ is in use and will not be installed
# Error in file(con, "r") : cannot open the connection
# In addition: Warning message:
# In file(con, "r") :
#  cannot open file 'C:/Users/jonathan.sidi/AppData/Local/Temp/RtmpARrTyF/R_LIBS5b00451d290a/details/R/details': No such file or directory
```

it seems to stem from this line in package_coverage

https://github.com/r-lib/covr/blob/a64413388cd5a6d635c8174bb930f4ed7e4ad0b1/R/covr.R#L313

i thought that `pre_clean` would clean out any dlls in windows that would cause the system to think the package is in use but that `clean_objects` is applied to `pkg$path` which is the local path of the package and not where the loaded dlls would be that would make install.packages lock up.

What am I doing wrong in this case? I know this is a winos specific issue since you cant install a loaded package on two concurrent r sessions if it is already loaded in one of them.

<details closed>
<summary> <span title='Click to Expand'> session info </span> </summary>

```r

- Session info ------------------------------------------------------------------
 setting  value                       
 version  R version 4.0.2 (2020-06-22)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  English_United States.1252  
 ctype    English_United States.1252  
 tz       America/New_York            
 date     2020-09-04                  

- Packages ----------------------------------------------------------------------
 package     * version date       lib source        
 assertthat    0.2.1   2019-03-21 [1] CRAN (R 4.0.2)
 backports     1.1.9   2020-08-24 [1] CRAN (R 4.0.2)
 cli           2.0.2   2020-02-28 [1] CRAN (R 4.0.2)
 clipr         0.7.0   2019-07-23 [1] CRAN (R 4.0.2)
 covr        * 3.5.0   2020-03-06 [1] CRAN (R 4.0.2)
 crayon        1.3.4   2017-09-16 [1] CRAN (R 4.0.2)
 desc          1.2.0   2018-05-01 [1] CRAN (R 4.0.2)
 details     * 0.2.1   2020-09-04 [1] local         
 fansi         0.4.1   2020-01-08 [1] CRAN (R 4.0.2)
 glue          1.4.2   2020-08-27 [1] CRAN (R 4.0.2)
 httr          1.4.2   2020-07-20 [1] CRAN (R 4.0.2)
 knitr         1.29    2020-06-23 [1] CRAN (R 4.0.2)
 lazyeval      0.2.2   2019-03-15 [1] CRAN (R 4.0.2)
 magrittr      1.5     2014-11-22 [1] CRAN (R 4.0.2)
 png           0.1-7   2013-12-03 [1] CRAN (R 4.0.0)
 R6            2.4.1   2019-11-12 [1] CRAN (R 4.0.2)
 rex           1.2.0   2020-04-21 [1] CRAN (R 4.0.2)
 rprojroot     1.3-2   2018-01-03 [1] CRAN (R 4.0.2)
 rstudioapi    0.11    2020-02-07 [1] CRAN (R 4.0.2)
 sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 4.0.2)
 withr         2.2.0   2020-04-20 [1] CRAN (R 4.0.2)
 xfun          0.16    2020-07-24 [1] CRAN (R 4.0.2)
 xml2          1.3.2   2020-04-23 [1] CRAN (R 4.0.2)

[1] C:/RHOME/win-library/4.0
[2] C:/Program Files/R/R-4.0.2/library

```

</details>
<br>

Thanks

**Comment by jimhester** [comment]
This is coming from `install.packages()`, there isn't really anything we can do.

Basically you shouldn't try to use covr with a package that is already loaded on windows.

**Comment by yonicd** [comment]
This wasn't an issue prior to R 4.0+. Do you know if there was a major change in how install.packages is implemented in that release to create this problem?

**Comment by jimhester** [comment]
It seems to have last been changed in R 4.0 (https://github.com/wch/r-source/commit/ebef82053567e2c2fed4507594ab318c05762866).

**Comment by yonicd** [comment]
the added `pkgs <- pkgs[!inuse]` seems to be borking the run. thanks
