### ISSUE TITLE
Failure if coverage RDS file is corrupt

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/covr#445]
This may happen if a subprocess is killed while writing out the coverage file. 

I don't think this should be ignored, but maybe a warning is enough?

**Comment by gaborcsardi** [comment]
Yes, it fails, `readRDS()` cannot read an incomplete RDS file.

It happens for things like this:
```r
fun <- function() {
  rs <- r_session()
  on.exit(rs$kill())
  rs$run(function() library(testthat))
  rs$call(function() quit('no', 0L, TRUE))
  stop("oops")
  ...
}
```

So if I have an `r_session` that is cleaned up either on an early exit or even a normal exit, then the subprocess might get killed while writing out the coverage data. 

In principle there is nothing wrong with this code, it just does not play well with covr. 

Also, it might take quite long to write out the data, e.g. in testthat I had a 1s grace period for the subprocesses to quit, but that is not enough, apparently: https://github.com/r-lib/testthat/blob/aa51fcf6462878b41134522d9500113728bea865/R/parallel.R#L277

**Comment by jimhester** [comment]
Does `rs$kill()` send `SIGTERM` or `SIGKILL`, the latter should really only be used for exceptional cases...

**Comment by gaborcsardi** [comment]
Since `SIGTEM` might be ignored/handled, and it is actually ignored by default in compiled code, you need to send a `SIGKILL` eventually.

**Comment by gaborcsardi** [comment]
Also, there is no `SIGTERM` on Windows.

**Comment by jimhester** [comment]
If you want coverage data you need to allow the processes to cleanly exit.

**Comment by gaborcsardi** [comment]
Got it.
