### ISSUE TITLE
Fail on GitHub Action

### ISSUE THREAD

**Issue by kadyb** [r-lib/covr#449]
Hi! I tried to run a [test-coverage script](https://github.com/r-lib/actions/blob/master/examples/test-coverage.yaml) on GitHub Actions but with [no success](https://github.com/kadyb/rgugik/actions/runs/266960704). I don't know exactly what the error is. `package_coverage` works fine locally on Windows 8.1. I use the **testit** package for testing.

Log:
```r

Run covr::codecov()
##[error]Error: Failure in `/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/Rtmpn0VzmN/R_LIBS7906e9c2cea/rgugik/rgugik-tests/test-all.Rout.fail`
ibute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library(testit)
> test_pkg('rgugik')
Linking to GEOS 3.8.1, GDAL 3.1.1, PROJ 6.3.1
Error from parse_and_simplify(txt = txt, simplifyVector = simplifyVector,  ... 
Error in parse_con(txt, bigint_as_char) : 
  lexical error: invalid char in json text.
                                       <html><head><title>Request Reje
                     (right here) ------^
Calls: test_pkg ... <Anonymous> -> parse_and_simplify -> parseJSON -> parse_con
Execution halted
Execution halted
##[error]Process completed with exit code 1.
```

**Comment by jimhester** [comment]
I don't think this is specific to covr. I think you will find your tests failing in the same way using R CMD check. However your tests are currently not running in R CMD check because you have `^test` in your `.Rbuildignore` file and the tests directory is being excluded from the built package.

**Comment by kadyb** [comment]
Thanks for your response. You were absolutely right that the tests in rcmdcheck will [fail](https://github.com/kadyb/rgugik/actions/runs/269287496). So the bug is probably from package **testit**. Thanks for the help!
