### ISSUE TITLE
Conditional exclusions would be nice

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/covr#453]
When some lines are only covered on Windows, for example, it would be nice to be able to write

```r
# nocov start is_windows()
some windows specific code
# nocov end
```

Otherwise when you don't get a full coverage, you need to go over the lines that were left out, only to realize that they are only covered on another platform.

**Comment by jimhester** [comment]
You can combine coverage reports from multiple systems, I think a better solution is to run your tests on both windows and whatever else and upload coverage reports from both.
