### ISSUE TITLE
covr::codecov() fails on GitHub Actions

### ISSUE THREAD

**Issue by jayrobwilliams** [r-lib/covr#461]
My package test coverage has stopped working on GitHub Actions and I can't find anything I've changed that should affect it. It worked two months ago just fine after switching form Travis to GitHub Actions, but I made some minor unrelated changes two days ago and now it no longer works. I get the following error, which happens when the runner tries to execute `covr::codecov()`:

```
Error: Error in file(con, "r") : cannot open the connection
Calls: <Anonymous> -> package_coverage -> add_hooks -> readLines -> file
In addition: Warning messages:
1: In utils::install.packages(repos = NULL, lib = tmp_lib, pkg$path,  :
  installation of package ‘/Users/runner/work/RWmisc/RWmisc’ had non-zero exit status
2: In file(con, "r") :
  cannot open file '/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/RtmpjZlwm8/R_LIBSad952e6f1d8/RWmisc/R/RWmisc': No such file or directory
```

Here's the most recent run: https://github.com/jayrobwilliams/RWmisc/runs/1671256597?check_suite_focus=true#step:6:1
And here's the last working one: https://github.com/jayrobwilliams/RWmisc/runs/1442773492?check_suite_focus=true#step:6:1

It's a public repo and I've added the Codecov app to the repo after the initial failure and that doesn't seem to have fixed it. I can run `covr::package_coverage()` locally using `covr` 3.5.1 with no issues at all, so I'm at a bit of a loss as to what's going on. Any help would be greatly appreciated.

**Comment by jimhester** [comment]
The issue is with system dependencies

```
  unable to load shared object '/Users/runner/work/_temp/Library/sf/libs/sf.so':
* removing ‘/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/RtmphwAUtD/R_LIBS78b32781957/RWmisc’
  dlopen(/Users/runner/work/_temp/Library/sf/libs/sf.so, 6): Library not loaded: /usr/local/opt/proj/lib/libproj.19.dylib
  Referenced from: /Users/runner/work/_temp/Library/sf/libs/sf.so
```

see https://github.com/jayrobwilliams/RWmisc/runs/1681328214?check_suite_focus=true#step:8:18

**Comment by jayrobwilliams** [comment]
Thank you! I'd added them in https://github.com/jayrobwilliams/RWmisc/commit/bb9440b4e77a373f6aac28614b63bdd68c79d73d but taken them out since it didn't seem to help. Looking back at that log, turns out the step to install the system dependencies was never actually triggered! Re-added the system dependencies without conditioning on the runner OS.
