### ISSUE TITLE
devtools::test_coverage() reports coverage but covr::package_coverage() &report() reports 0.00% coverage

### ISSUE THREAD

**Issue by mccroweyclinton-EPA** [r-lib/covr#466]
Good morning, I have created a fairly new package and I am currently cleaning it up. As part of this process I am utilizing covr to manage unit testing. For some reason devtools::package_coverage() seems to accurately report unit test coverage but covr::package_coverage() and covr::report() reports 0.00% coverage. This is confusing to me since the  devtools::test_coverage() documentation states that it is simply a wrapper around covr::package_coverage() and covr::report(). My package, for reprex, can be found [here](https://github.com/USEPA/RAQSAPI/tree/Github_action).

**Comment by jimhester** [comment]
All of your tests have `testthat::skip_on_cran()`, `covr::package_coverage()` runs the tests as in the exact same way that CRAN does, e.g. it has no knowledge of devtools or testthat. In particular it does not set the `NOT_CRAN` environment variable, which is how testthat / devtools denotes if a test is running 'on CRAN' or not.

run `Sys.setenv(NOT_CRAN = "true")` before calling `covr::package_coverage()` or `covr::report()` if you want these tests to run.

**Comment by cjmc00** [comment]
Thank you, so does devtools::test_coverage() set this environment variable before running, why does it not have the same output?

**Comment by mccroweyclinton-EPA** [comment]
Thank you, so does devtools set this environment variable before running, why does devtools::test_report not experience the same issue?
