### ISSUE TITLE
Output of `file_coverage()` does not contain attribute `package$path`

### ISSUE THREAD

**Issue by msberends** [r-lib/covr#478]
Thanks for this package.

Since a short while ago, we use `tinytest` for unit testing, since it is dependency-free. The `tinytest` package requires users to add their tests to `inst/tinytest`, which is not picked up by `covr:package_coverage()`. Whether `tinytest` should be supported by `covr` is another issue, I'm here now for your implementation of manual supporting other ways of picking up unit tests. 

So as a workaround we now use `covr::file_coverage()`, but it does not contain a `path` argument and nor does it contain `...` to pass on other arguments. Consequently, the output of the functions does not contain an attribute `package` with the list item `package$path`. This last list item is required for uploading:

```r
source_files <- list.files("R", pattern = ".R$", full.names = TRUE)
test_files <- list.files("inst/tinytest", full.names = TRUE)
cov <- covr::file_coverage(source_files = source_files, test_files = test_files)
covr::codecov(coverage = cov, quiet = FALSE)
#> Error in if (file.exists(path_to_yaml)) { : argument is of length zero
```

I think that the error is derived from the `extract_from_yaml()` function in this line when `token` is not set (in my case, it's the environmental variable `CODECOV_TOKEN`):

https://github.com/r-lib/covr/blob/c6d10d9b6ffec0521e49eb5388f5e3a6d47e4bd7/R/codecov.R#L197

The hack is quite straightforward though:

```r
attr(cov, which = "package") <- list(path = ".")
covr::codecov(coverage = cov, quiet = FALSE)
#> $message
#> [1] "Coverage reports upload successfully"
#> 
#> $uploaded
#> [1] TRUE
#> 
#> (...)
```

So I reckon the `file_coverage()` or the `extract_from_yaml()` function requires a small fix 🙂

**Comment by jimhester** [comment]
covr works fine with any testing framework, it simply sources the files in your `tests/` directory, if covr is not working for your package your tests are not running in `R CMD check` either.

Your [AMR](https://github.com/msberends/AMR) package works fine with `covr::test_package()` as long as you set `Sys.setenv("R_RUN_TINYTEST" = "true")` before running the coverage.

**Comment by msberends** [comment]
That's of course true! Oh my, now I feel a bit ashamed 😞 

Thanks for checking the code and pointing me into the right direction! This issue is a false-positive.
