### ISSUE TITLE
Sudden drop in coverage percentage?

### ISSUE THREAD

**Issue by krassowski** [r-lib/covr#486]
I am seeing a drop of 18% in coverage percentage on https://app.codecov.io/gh/krassowski/complex-upset which cannot be attributed to any change in the tests or code. The run was triggered by pull request: https://github.com/krassowski/complex-upset/pull/129 and I wonder why this happened.

There does not seem to have been any release in the last two months and I checked that the build uses 3.5.1 version. Is there something obvious that I am missing? Sorry if this is a dumb question!

**Comment by krassowski** [comment]
To confirm the issue I created a fresh PR by adding a simple space in README.md: https://github.com/krassowski/complex-upset/pull/130 and I observer the same drop. Could it be an incompatibility with a newer testthat version (3.0.4 vs 3.0.2 that was installed the last time the tests were run)? What else should I check?

**Comment by jimhester** [comment]
It is possible this was due to changes in a dependency. vdiffr has had a fairly recent release, perhaps this has changed how your tests are run.

**Comment by krassowski** [comment]
Indeed there is a different version of vdiffr in use (1.0.2 vs earlier 0.3.3).
