### ISSUE TITLE
Add an option to report source-root-relative paths

### ISSUE THREAD

**Issue by krlmlr** [r-lib/covr#497]
`covr::package_coverage()` uses paths relative to the root of the R package by default, or absolute paths with `relative = FALSE` . None of these options is great for repositories where the R package sits underneath some subdirectory (duckdb, arrow, igraph, ...) . The problem occurs when trying to upload these coverage reports to codecov or other services. See e.g. https://codecov.io/gh/duckdb/duckdb/compare/624fa8aa4d81f812d7dc8d83620f914a76b3b114...e675b3dce58b120ca87574736f4c2386c1ddbcce/changes: this PR adds coverage checks for the R package that lives in `tools/rpkg` (via `covr::codecov("tools/rpkg")` but the files are not referred to by their relative root. This causes confusion with the other coverage checks in the project.

I propose supporting a third option, e.g. `relative = "wd"` or perhaps `relative = getwd()` where all paths would be stored relative to the working directory. Fixing this here is way easier than working around at the user level, it is very cumbersome to tweak the data structure returned by `covr::package_coverage()` .

**Comment by jimhester** [comment]
You should be able to adress this by using the path fixing configuration in codecov.yml https://docs.codecov.com/docs/fixing-paths

**Comment by krlmlr** [comment]
Thanks, I wasn't aware of that. It seems difficult in the current case because there is both a `src` and a `tools/rpkg/src` directory, and we get coverage reports for both. AFAICT `codecov.yml` affects the whole repository?

I have a PR almost ready though.

**Comment by jimhester** [comment]
You can have multiple different fixes active at the same time

**Comment by krlmlr** [comment]
Good catch, that might even work for this particular use case. It's not very pretty though.

**Comment by krlmlr** [comment]
I tried path rewriting, it's much more difficult than creating reports with correct paths.
