### ISSUE TITLE
`covr::codecov()` upload to codecov.io fails with 503 error

### ISSUE THREAD

**Issue by jabenninghoff** [r-lib/covr#512]
`covr::codecov()` recently started failing to upload code coverage reports to codecov.io with a 503 Service Unavailable Error.

This behavior exists when running interactively in the RStudio Console and GitHub Actions.

Interactive example:

```r
covr::codecov()
#> Request failed [503]. Retrying in 1 seconds...
#> Request failed [503]. Retrying in 2.1 seconds...
#> No encoding supplied: defaulting to UTF-8.
#> [1] "no healthy upstream"
```

GitHub Action [example](https://github.com/jabenninghoff/cards/runs/7437140079?check_suite_focus=true).

This behavior has been observed in multiple projects, including [devtools](https://github.com/r-lib/devtools/actions/workflows/test-coverage.yaml) and [data.table](https://github.com/Rdatatable/data.table/actions/workflows/test-coverage.yaml). From the data.table logs, the last successful run was on [July 19](https://github.com/Rdatatable/data.table/runs/7403578650?check_suite_focus=true).

https://status.codecov.com is reporting all systems operational.

**Comment by willgearty** [comment]
Looks like it might be a broader codecov.io issue: https://community.codecov.com/t/503-service-unavailable-no-healthy-upstream/3762

**Comment by willgearty** [comment]
The problem appears to be resolved now! The codecov [status page](https://status.codecov.com/) lists multiple SSL issues over the last couple days which I'm guessing are to blame.

**Comment by jabenninghoff** [comment]
It is indeed resolved. https://status.codecov.com/ did not show any issues yesterday, but this is clearly not a `covr` problem. closing.
