### ISSUE TITLE
`covr::package_coverage()` fails with error cannot open connection

### ISSUE THREAD

**Issue by sempwn** [r-lib/covr#520]
I'm working on adding `covr`  to my R package (see most recent [pull request](https://github.com/sempwn/bennu/pull/2). Currently I have set up a Github Action to run `covr::codecov()`  from [test-coverage.yaml](https://github.com/sempwn/bennu/blob/dev/.github/workflows/test-coverage.yaml). I have also ran `covr::codecov()` and `covr::package_coverage()` directly from the project. In all three instances I receive the same error

[``` r Error: Error in file(con, "r") : cannot open the connection```](https://github.com/sempwn/bennu/actions/runs/3707942387/jobs/6284957537#step:5:22)

I tried following suggestions indicated in issue #354 but to no avail. Any advice would be very much appreciated!

**Comment by jimhester** [comment]
Your `configure` script did not have the executable bit set, so it was not getting run. `chmod u+x configure` fixed the issue for me.

**Comment by sempwn** [comment]
@jimhester That worked thank you! 

Leaving a note here for how I solved it to anyone else who encounters this issue and developing in a Windows environment. I had to launch `wsl` from Windows, clone my package into the Linux environment, run the fix above and then commit and push the configure file from Linux.
